Маршрут по тайным тропам
GoveRaven/what-to-watch pull request #3
Opened 2024-05-18 17:01 UTC by GoveRaven

2024-05-19 10:46 UTC, Lexeria requested changes

2024-05-19 10:46 UTC, Lexeria commented on project/src/components/app/app.tsx
> +            <PrivateRoute authorizationStatus={AuthorizationStatus.Auth}>
> Пока мы не взаимодействуем с настоящим сервером, передавайте компоненту информацию, что пользователь всегда НЕ авторизован

2024-05-19 10:46 UTC, Lexeria commented on project/src/components/app/const.tsx
Эти константы не только для компонента `App` нужны, они могут быть потенциально быть использованы везде — как в обычных компонентах, так и на страничках. Для этого обычно создают папку `consts` и в нее добавляют файлы, имя которых логически отображает, что за константные сущности будут там располагаться

2024-05-19 10:46 UTC, Lexeria commented on project/src/components/app/private-route.tsx
Это компонент не часть компонента `App`, вытащи лучше в папку со всеми компонентами

2024-05-19 10:46 UTC, Lexeria commented on project/src/pages/page-not-found.tsx
Напомню про семантический нейминг — у тебя этот компонент в папочке `pages`. Можно файл и название компонента использовать без слова `page`

2024-05-19 10:52 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +            <PrivateRoute authorizationStatus={AuthorizationStatus.Auth}>
сделал

2024-05-19 10:59 UTC, GoveRaven commented on project/src/components/app/const.tsx
сделал

2024-05-19 11:00 UTC, GoveRaven commented on project/src/components/app/private-route.tsx
сделал

2024-05-19 11:01 UTC, GoveRaven commented on project/src/pages/page-not-found.tsx
сделал

2024-05-20 05:52 UTC, Lexeria requested changes

2024-05-20 05:52 UTC, Lexeria commented on project/src/consts/Routes.tsx
Название файла стоит начинать с маленькой буквы

2024-05-20 05:52 UTC, Lexeria commented on project/src/consts/Routes.tsx
> +export enum RoutesConsts {
Можно оставить старое название, так как речь идет про маршруты в рамках приложения, что будет так же `App`, как и одноименный компонент, где раньше этот файл был

2024-05-20 05:52 UTC, Lexeria commented on project/src/consts/Routes.tsx
> +export enum RoutesConsts {
В названиях файла мы не используем фразы `Consts` — для этого мы пользуемся названием файла или папкой семантической, как в нашем случае, чтоб подчеркнуть, что внутри все про константные значения

2024-05-20 05:52 UTC, Lexeria commented on project/src/components/app/app.tsx
> +import { PageNotFound } from '../../pages/not-found';
Компонент тоже можно переименовать, чтобы убрать излишнее `Page`, но если есть желание оставить, то стоит правильный порядок использовать — `NotFoundPage`

2024-05-20 09:44 UTC, Lexeria approved these changes

2024-05-20 09:44 UTC, merged