Обратная сторона реальности
GoveRaven/what-to-watch pull request #4
Opened 2024-05-25 15:40 UTC by GoveRaven

2024-05-25 16:16 UTC, Lexeria requested changes

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/app/app.tsx
> +type AppProps = MainProps
А чего точка с запятой пропала?

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/app/app.tsx
> +            <PrivateRoute authorizationStatus={AuthorizationStatus.Auth}>
Ахах, так и быть, пусть остается так, чтобы разрабывать удобно было пока

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/app/app.tsx
> +        <Route path={AppRoutes.AddReview} element={<AddReview film={films[0]}/>} />
Пока `fims[0]` норм, но на будущее подсвечу, что тут скорее всего пропадет этот пропс и ты с помощью хука `useParams` (или другого, не помню уже) будешь доставать айдишник фильма и отправлять запрос на получение фильма на сервер

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/films-list.tsx
> +  // const [activeCard, setActiveCard] = useState();
Кажется, забыл логику реализовать. Там предлагают два варианта:

> объект с данными фильма или лишь уникальный идентификатор фильма

Предлагаю хранить лишь айдишник, и здесь переименовать на `activeCardId` и `setActiveCardId`

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/films-list.tsx
> +          id = {film.id}
У нас обычно без пробелов, видимо, преттир не прошелся. А там ворнингов хотя бы на эту штуку нет?

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/review-form.tsx
> +          </label>
Не факт, что это будет дальше предлагать порефачить, на всякий случай давай добавим вверху комментарий с префиксом `TODO:`. Например, `TODO: порефачить отрисовку radio-кнопок ниже`

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +import { Link } from 'react-router-dom';
Порядок импортов странный, тут нет ворнингов? Преттир прошелся?

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/add-review.tsx
>          <div className="add-review">
По идее, этот див тоже можно было утащить в компонент с формой, чтобы в разных местах у нас была форма с такими же стилями

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/main.tsx
> +            <FilmList films={films} key="List" />
Тут ключ лишний, и ты можешь увидеть, откуда ноги проросли и почему он тут остался — до этого ты рисовал через `map`, то есть несколько компонентов за раз в одном месте. Чтобы реакт понимал, где и какой компонент — важно было дать ему это понять через ключевой пропс `key`. Сейчас же у нас тут один компонент — `FilmList`. Его реакт отрисует нормально, а вот внутри `FilmList` ты используешь отрисовку элементов через `map`, где `key` уже нужен

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/my-list.tsx
> +import { Link } from 'react-router-dom';
Тоже порядок импортов странный. Преттир прошелся, ворнингов нет?

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/player.tsx
> +        <button type="button" className="player__exit" onClick={() => navigate(AppRoutes.Main)}>
Я думаю, тут надо возвращаться не на главную, а в то место, откуда был открыт плеер, то есть на предыдущую страницу. Для этого мы можем передать что-то в духе `navigate(-1)` — вернись на 1 страницу назад

2024-05-25 16:16 UTC, Lexeria commented on project/src/consts/routes.tsx
> +  Film = '/film/:id',
А почему тут путь поменялся? Он был правильный `films/:id`. Тип семантически мы обращаемся так: `films` — страничка со всеми фильмами, `films/:id` — углубиться от этого списка к фильму с определенным айдишником. То есть `films` — название коллекции с фильмами, как массив, к которому мы по айдишнику обращаемся потом через слэш

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/movie.tsx
> +                  onClick={() => navigate(AppRoutes.Player)}
Нам нужен `Player` для конкретного фильма с этой странички. Для этого можно воспользоваться хуком `useParams`

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/movie.tsx
> +                  onClick={() => navigate(AppRoutes.MyList)}
Это не ссылка, а добавление в список фильм. Тут потом будет определенное действие, но без роутинга, навигировать не надо

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/movie.tsx
> +                <Link to={AppRoutes.AddReview} className="btn film-card__button">
Тут тоже аналогично, что это не просто `AddReview`, а `AddReview` для конкретного фильма

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/movie.tsx
>  export function MoviePage(): JSX.Element {
Давай пока хотя бы пропсом получим любой фильм и тут обновим информацию о нем. Тут ниже можно поменять информацию о дате выхода, рейтинге, жанре, названии, постере, режиссере, количестве оценок, описанию

2024-05-25 16:16 UTC, Lexeria commented on project/src/components/app/app.tsx
> +        <Route path={AppRoutes.AddReview} element={<AddReview film={films[0]}/>} />
Аналогично будет для странички с фильмом, только ты туда пока фильм не передавал

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/main.tsx
> +                  onClick={() => navigate(AppRoutes.Player)}
Тут тоже не просто плеер, нужно навигировать на конкретную страничку

2024-05-25 16:16 UTC, Lexeria commented on project/src/pages/main.tsx
> +                  onClick={() => navigate(AppRoutes.MyList)}
Тут та же историю про добавление в список — лучше пока убрать `onClick`, тут будет другое действие

2024-05-25 16:32 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +type AppProps = MainProps
пропала, но вернул

2024-05-25 16:34 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +            <PrivateRoute authorizationStatus={AuthorizationStatus.Auth}>
я без этого не мог зайти на страницы My List и Player

2024-05-25 16:37 UTC, GoveRaven commented on project/src/components/films-list.tsx
> +  // const [activeCard, setActiveCard] = useState();
там пока не нужно реализовывать это. Цитирую:

> Состояние пригодится нам в дальнейшем для реализации воспроизведения видео по наведению на карточку фильма.
Закомментил я её, чтобы сообщение о неиспользовании глаза не мозолила

2024-05-25 16:40 UTC, GoveRaven commented on project/src/components/films-list.tsx
> +          id = {film.id}
ворнингов не было. Преттир прошёлся и пробелы ушли

2024-05-25 16:42 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +          </label>
добавил

2024-05-25 16:43 UTC, GoveRaven commented on project/src/pages/add-review.tsx
> +import { Link } from 'react-router-dom';
ворнингов нет. Преттир прошёлся. А что не так с импортом?

2024-05-25 17:26 UTC, GoveRaven commented on project/src/pages/add-review.tsx
>          <div className="add-review">
сделал

2024-05-25 17:27 UTC, GoveRaven commented on project/src/pages/main.tsx
> +            <FilmList films={films} key="List" />
и вправду лишний. Убрал

2024-05-25 17:28 UTC, GoveRaven commented on project/src/pages/my-list.tsx
> +import { Link } from 'react-router-dom';
прошёлся

2024-05-25 17:30 UTC, GoveRaven commented on project/src/pages/player.tsx
> +        <button type="button" className="player__exit" onClick={() => navigate(AppRoutes.Main)}>
не знал о такой штуке. Исправил

2024-05-25 17:31 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +                  onClick={() => navigate(AppRoutes.Player)}
я понимаю, что там нужен определённый фильм, но пока просили сделать маршрутизацию на всё сайте. + я пока не разобрался как для отдельных сайтов отдельные странички делать с отдельными плеерами. Поэтому пока без этого

2024-05-25 17:32 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +                  onClick={() => navigate(AppRoutes.MyList)}
понял. Убрал

2024-05-25 17:32 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +                <Link to={AppRoutes.AddReview} className="btn film-card__button">
аналогичный комментарий. Просили сделать только маршрутизацию. Позже сделаю, чтобы переходило на отдельные фильмы

2024-05-25 18:09 UTC, GoveRaven commented on project/src/pages/movie.tsx
>  export function MoviePage(): JSX.Element {
сделал

2024-05-25 18:09 UTC, GoveRaven commented on project/src/pages/main.tsx
> +                  onClick={() => navigate(AppRoutes.Player)}
тот же комментарий выше

2024-05-25 18:10 UTC, GoveRaven commented on project/src/pages/main.tsx
> +                  onClick={() => navigate(AppRoutes.MyList)}
понял. Убрал

2024-05-26 08:06 UTC, Lexeria commented on project/src/components/app/app.tsx
> +            <PrivateRoute authorizationStatus={AuthorizationStatus.Auth}>
Ага, пусть остается пока так

2024-05-26 08:06 UTC, Lexeria commented on project/src/components/films-list.tsx
> +  // const [activeCard, setActiveCard] = useState();
Пригодится в дальнейшем, но реализовать просить сейчас и предлагают два варианта

2024-05-26 08:08 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +import { Link } from 'react-router-dom';
Обычно есть определенный порядок: сначала импорты из библиотек, потом из папок уровней выше, потом из текущей папки. Или любой другой, как договорились в проекте, на это настраивают правило линтера

2024-05-26 08:08 UTC, Lexeria commented on project/src/pages/my-list.tsx
> +import { Link } from 'react-router-dom';
Аналогично про порядок импортов просто

2024-05-26 08:12 UTC, Lexeria commented on project/src/pages/movie.tsx
> +                  onClick={() => navigate(AppRoutes.Player)}
В 9 пункте просят связать странички приложения. Тут сейчас нет связи с айдишником фильма, в любом случае придется это править, я не помню будет ли потом что-то про это, поэтому предлагаю поправить сейчас

Айдишник текущего фильма можно получить двумя способами пока:
1. Прокинув через пропс моковый фильм
2. Из браузерной строчки через `useParams`

2024-05-26 08:13 UTC, Lexeria commented on project/src/pages/movie.tsx
> +                <Link to={AppRoutes.AddReview} className="btn film-card__button">
Тоже добавлю аналогичное про связывание страничек, которое сейчас не полноценное

2024-05-26 08:13 UTC, Lexeria commented on project/src/pages/main.tsx
> +                  onClick={() => navigate(AppRoutes.Player)}
Тот же коммент выше

2024-05-26 08:17 UTC, Lexeria requested changes

2024-05-26 08:17 UTC, Lexeria commented on project/src/pages/movie.tsx
> +export function MoviePage(props: MoviePageProps): JSX.Element {
Тут можно `film` деструктуризацией достать

2024-05-26 09:47 UTC, GoveRaven commented on project/src/consts/routes.tsx
> +  Film = '/film/:id',
я подумал, что страничка с фильмом должна называться film, а не films, ведь фильм один. Поэтому переименовал. Верну назад

2024-05-26 14:29 UTC, Lexeria approved these changes

2024-05-26 14:49 UTC, merged