Больше подробностей
GoveRaven/what-to-watch pull request #5
Opened 2024-06-15 18:51 UTC by GoveRaven

2024-06-19 03:17 UTC, Lexeria requested changes

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/film-card.tsx
> +        timerID = setTimeout(setActiveCardID, 1000, id);
Респект за 3 аргумент

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/films-list.tsx
> +  isMoviePage: boolean;
Кажется, что можно обойтись без этого пропса. У тебя есть мощный инструмент для манипуляций и получении информации о роутинге — react router. Есть много различных хуков с помощью, которых можно понять, на какой сейчас странички мы находимся

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/films-list.tsx
>    // const [activeCardID, setActiveCardID] = useState();
Может удалить отсюда, или еще понадобится?

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/films-list.tsx
> +      .filter((film) => film.genre === genre && films.length)
А к чему в конце постоянная проверка на `length`?

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/details.tsx
> +type DetailsProps = {
Стоит соблюдать единый стиль и у типов в начале добавлять букву `T`

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/details.tsx
> +  function culcRunTime(): string {
Лучше вытащить за компоненту, чтобы на каждый рендер заново не объявлять эту функцию. Если не понятно, о чем говорю, можем созвониться как-нибудь

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/details.tsx
> +                {person} <br />
Там без запятых выводятся?

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/overview.tsx
> +export type OverviewProps = {
Аналогично про букву `T`

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/overview.tsx
> +  function addStarring(): string {
Аналогично про вынес функции за пределы компонента

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/overview.tsx
> +  function addStarring(): string {
Кажется, ты написал аналог функции `join`. У тебя еще, возможно, лишний пробел в конце стоит тут только в последней строчке

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  function getDate(date: string) {
Тоже лучше вынести за пределы компонента

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +    const mounth = [
Массивы обычно принято называть во множественном числе. Туть еще очепятка, правильно. `month`

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +    const fullDate: Date = new Date(Date.parse(date));
Тут должен хорошо отработать автовывод типов, не обязательно указывать его явно

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +    const fullDate: Date = new Date(Date.parse(date));
Кажется, можно оставить только конструктор `Date`, он под капотом и так [будет использовать](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#datestring) `Date.parse`

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +      {/* // TODO
Буду ждать. Тут только перенос лишний, обычно пишут как-то так: `@todo do smth` или `TODO: do smth`. А может еще как-то)

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +      {/* // TODO
Тут получился комментарий комментария

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +        const { name } = user;
В принципе, можно было не вытаскивать в переменные, так как они почти не повторяются, а названия не слишком длинные

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/tabs.tsx
> +type TabsProps = {
Тоже `T` в начале не хватает

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/tabs.tsx
> +  reviews = 'Reviews',
Названия у перечислений (енамов) обычно пишутся хотя бы с большой буквы, или полностью капсом, а само значение может быть хоть с маленькой — как удобно

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/tabs/tabs.tsx
> +          <li className={`film-nav__item ${activeTab === TabsName.overview && 'film-nav__item--active'}`}>
Заметь, что у тебя повторяется логика для определения навешивания класса для активного таба. Если будут добавляться еще табы, то ты будешь копировать эту логику в несколько мест, а при необходимости поменять — будешь менять в нескольких местах, а не одном. Советую подумать, как можно это улучшить, есть несколько вариантов)

2024-06-19 03:17 UTC, Lexeria commented on project/src/components/video-player.tsx
> +export type VideoPlayerProps = {
Буква `T` на барабане

2024-06-19 03:17 UTC, Lexeria commented on project/src/pages/main.tsx
> +            <FilmList films={films} isMoviePage={false} />
От этого пропса все же лучше избавиться

2024-06-19 03:17 UTC, Lexeria commented on project/src/pages/movie.tsx
> +          {/* <div className="catalog__films-list">
Закоменченные элемент точно нужен?

2024-06-19 03:17 UTC, Lexeria commented on project/src/types/reviews.tsx
> +export type TReviews = {
А это точно тип для для нескольких ревью, а не одного?

2024-06-19 16:29 UTC, GoveRaven commented on project/src/components/film-card.tsx
> +        timerID = setTimeout(setActiveCardID, 1000, id);
до меня долго не доходило как кинуть функцию с аргументом в setTimout, поэтому я полез в учебник и прочитал, что есть третий аргумент

2024-06-19 16:30 UTC, GoveRaven commented on project/src/components/films-list.tsx
> +      .filter((film) => film.genre === genre && films.length)
Это не должно было попасть в итоговую версию

2024-06-19 16:32 UTC, GoveRaven commented on project/src/components/tabs/details.tsx
> +                {person} <br />
в деталях выводят каждого актёра на новой строке, в overview через запятую

2024-06-19 16:43 UTC, GoveRaven commented on project/src/components/films-list.tsx
>    // const [activeCardID, setActiveCardID] = useState();
хз, но пока уберу

2024-06-19 16:44 UTC, GoveRaven commented on project/src/components/tabs/details.tsx
> +  function culcRunTime(): string {
мне понятно зачем стоит вынести функцию за компоненту. Сделал

2024-06-19 16:47 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  function getDate(date: string) {
сделал

2024-06-19 16:47 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +    const mounth = [
переименовал

2024-06-19 16:47 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +    const fullDate: Date = new Date(Date.parse(date));
Date.parse(date) убрал

2024-06-19 16:49 UTC, GoveRaven commented on project/src/components/tabs/tabs.tsx
> +  reviews = 'Reviews',
переименовал в капслок

2024-06-19 16:49 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +          {/* <div className="catalog__films-list">
убрал

2024-06-19 17:56 UTC, Lexeria commented on project/src/components/film-card.tsx
> +        timerID = setTimeout(setActiveCardID, 1000, id);
Самое любимое, это лишняя обертка)
`() => setActiveCardID(id)`, тогда мы и функцию не вызовем, и аргумент передадим. Но так лучше не делать, есть же 3 аргумент

2024-06-19 18:00 UTC, Lexeria commented on project/src/components/app/app.tsx
> +import { Main, TMainProps as TMainProps } from '../../pages/main';
Забавный алиас

2024-06-20 09:30 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +import { Main, TMainProps as TMainProps } from '../../pages/main';
убрал

2024-06-20 09:36 UTC, GoveRaven commented on project/src/components/tabs/overview.tsx
> +  function addStarring(): string {
и вправду изобрёл метод `join`. Переписал

2024-06-20 09:41 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +        const { name } = user;
убрал

2024-06-20 10:02 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +      {/* // TODO
сделал

2024-06-20 11:58 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +import { Main, TMainProps as TMainProps } from '../../pages/main';
исправил

2024-06-20 13:38 UTC, GoveRaven commented on project/src/components/films-list.tsx
> +  isMoviePage: boolean;
сделал

2024-06-20 15:09 UTC, Lexeria requested changes

2024-06-20 15:09 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +        {reviews1.map((review) => (
У тебя вышло дважды дублирование для ревью, лучше вытащить в отдельный компонент ревью

2024-06-20 15:09 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  const reviews2 = reviews.slice(halfOfReviews);
Лучше более осознанные имена давать для переменных, например, `firstReviewsHalf` и `secondReviewsHalf`

2024-06-21 04:41 UTC, Lexeria approved these changes
Все нормально, только название файла поменять не забудь

2024-06-21 05:38 UTC, merged