Контроль и ограничения
GoveRaven/what-to-watch pull request #6
Opened 2024-06-25 17:43 UTC by GoveRaven

2024-06-25 18:29 UTC, Lexeria requested changes

2024-06-25 18:29 UTC, Lexeria commented on project/src/components/genreList.tsx
> +  films.map((film) => genres.includes(film.genre) || genres.push(film.genre));
Подскажи, к чему эта строчка тут? `map` не мутирует исходный массив, а возвращает новый. Получается, что результат никуда не записывается сейчас и сама строчка ради `push` только. А если бы и мутировала, то тоже было бы не очень, так как не очень хорошо мутировать исходные аргументы

2024-06-25 18:29 UTC, Lexeria commented on project/src/components/genreList.tsx
> +  films.map((film) => genres.includes(film.genre) || genres.push(film.genre));
Я вижу, какую логику ты пытаешься преследовать, на всякий случай подскажу еще про существование `Set`

2024-06-25 18:29 UTC, Lexeria commented on project/src/components/genreList.tsx
> +              dispatch(FilterFilmsByGenre());
Название действия с большой буквы стало почему-то, хотя выше с маленькой

2024-06-25 18:29 UTC, Lexeria commented on project/src/components/genreList.tsx
> +              dispatch(FilterFilmsByGenre());
Вообще, из-за названия ощущение, что он ожидает `genre` в качестве аргумента. По-хорошему он должен называться как-то в духе `actualizeFilmListByActiveGenre`, но оно слишком длинное, можно подумать, как сократить, мб просто `actualizeFilmList`

2024-06-25 18:29 UTC, Lexeria commented on project/src/hooks/index.ts
> +export const useAppSelector: TypedUseSelectorHook<TState> = useSelector;
Это строчки из лайва в принципе, будет круто, если ты поделишься пониманием того, как работает здесь типизация и на что она влияет в коде, который ты пишешь

2024-06-25 18:29 UTC, Lexeria commented on project/src/hooks/index.ts
> +import { useSelector } from 'react-redux';
У тебя уже есть импорт из `react-redux` выше, можно убрать эту строчку и дополнить там список

2024-06-25 18:29 UTC, Lexeria commented on project/src/index.tsx
> +import { store } from './store';
Видимо, ребята не завезли линтинг на правила импортов, но просто можешь заметить, что сейчас небольшая каша в порядке импортов и неудобно в случае чего по ним перемещаться. Если не понятно почему — могу попытаться объяснить

2024-06-25 18:29 UTC, Lexeria commented on project/src/index.tsx
> +  <Provider store={store}>
Нужно все-таки обернуть только `App`. `React.StrictMode` не будет консьюмером этого провайдера + стоит в `StrictMode` оборачивать все приложение целиком, а не становиться чьим-то ребенком, теряя из вида некоторые компоненты. Зачем? Можно прочитать в [доке](https://react.dev/reference/react/StrictMode)

2024-06-25 18:29 UTC, Lexeria commented on project/src/pages/main.tsx
> +            <FilmList films={filmsFromStore} />
Почему тут `filmsFromStore`, а выше просто `films` из моковых данных? Мб стоит избавиться от этого пропса и перестать прокидывать его из `App`?

2024-06-25 18:29 UTC, Lexeria commented on project/src/components/genreList.tsx
Название файлов лучше писать в едином стиле и `snake-case`

2024-06-25 18:29 UTC, Lexeria commented on project/src/store/actions.ts
> +const FilterFilmsByGenre = createAction('films/getFilmList');
Название переменной поменял, а внутри название экшна осталось

2024-06-25 18:29 UTC, Lexeria commented on project/src/store/actions.ts
> +const FilterFilmsByGenre = createAction('films/getFilmList');
В целом, это идейно про одну зону ответственности — фильмы. Так что у обоих можно сделать префикс `films/`

2024-06-25 18:29 UTC, Lexeria commented on project/src/store/reducer.ts
> +  genre: 'All genres',
Заметь, что у тебя `All genres` дублируется в нескольких местах: на этой строчке, на 16-й, а еще в другом файле (`genreList.tsx`) на 10-й. Так легко очепятаться и сломать логику, советую вытащить в константу и обозвать как-то в духе `DEFAULT_GENRE`

2024-06-25 18:29 UTC, Lexeria commented on project/src/types/store.ts
> +export type TAppDispatch = typeof store.dispatch;
Тут тоже хочется послушать про понимание типизации, чтобы не упустить этот момент в дальнейшем и самому писать такие типы уметь

2024-06-25 18:29 UTC, Lexeria commented on project/src/components/genreList.tsx
Когда пишут ключевое слово `list` или что-то, что обозначает какое-то множество чего-то, то принято писать во множественном числе — `genres-list`

2024-06-26 08:01 UTC, GoveRaven commented on project/src/components/genreList.tsx
переименовал

2024-06-26 08:04 UTC, GoveRaven commented on project/src/store/actions.ts
> +const FilterFilmsByGenre = createAction('films/getFilmList');
сделал

2024-06-26 08:04 UTC, GoveRaven commented on project/src/components/genreList.tsx
> +              dispatch(FilterFilmsByGenre());
переименовал

2024-06-26 08:05 UTC, GoveRaven commented on project/src/hooks/index.ts
> +import { useSelector } from 'react-redux';
исправил

2024-06-26 08:06 UTC, GoveRaven commented on project/src/index.tsx
> +  <Provider store={store}>
исправил

2024-06-26 08:08 UTC, GoveRaven commented on project/src/store/actions.ts
> +const FilterFilmsByGenre = createAction('films/getFilmList');
исправил

2024-06-26 08:10 UTC, GoveRaven commented on project/src/store/reducer.ts
> +  genre: 'All genres',
добавил константу и заменил

2024-06-26 08:18 UTC, GoveRaven commented on project/src/pages/main.tsx
> +            <FilmList films={filmsFromStore} />
сделал

2024-06-26 11:47 UTC, GoveRaven commented on project/src/components/genreList.tsx
> +  films.map((film) => genres.includes(film.genre) || genres.push(film.genre));
поменял map на forEach

2024-06-26 11:49 UTC, GoveRaven commented on project/src/index.tsx
> +import { store } from './store';
если я правильно понимаю, то сначала нужно писать импорты из библиотек и прочего такого, а потом уже из папок проекта

2024-06-26 11:53 UTC, GoveRaven commented on project/src/hooks/index.ts
> +export const useAppSelector: TypedUseSelectorHook<TState> = useSelector;
на сколько я понимаю, мы задаём джейнерик и тип для хуков, которые предоставляет Redux, и записываем их в переменные. Получаем те же хуки, но они знают о типах данных в нашем хранилище, а поэтому могут подсказывать всё то, что подсказывает TS (куда можно передать значения, какие методы могут быть использованы и т.д.)

2024-06-26 11:57 UTC, GoveRaven commented on project/src/types/store.ts
> +export type TAppDispatch = typeof store.dispatch;
тут у меня такое же объяснение, что и к хукам

2024-06-26 12:42 UTC, Lexeria commented on project/src/types/store.ts
> +export type TAppDispatch = typeof store.dispatch;
Понятен оператор `typeof` и логика вывода типа на основе стора?

2024-06-26 12:44 UTC, Lexeria commented on project/src/hooks/index.ts
> +export const useAppSelector: TypedUseSelectorHook<TState> = useSelector;
В целом да, без тс нам не подсказывают обычно какие экшны можем диспатчить, какой тип вернет стейт и все в этом духе. Благодаря этому ошибиться в мире редакса, где все разбросано по разным частям, будет тяжеловато, а писать код приятнее и быстрее

2024-06-26 12:45 UTC, Lexeria commented on project/src/index.tsx
> +import { store } from './store';
Не обязательно, это как договариваетесь в команде/проекте, над которым работает. Но единый стиль лучше всегда, чем его отсутствие. Я привык сначала импорт из библиотек, потом из папок уровней выше, а потом в текущем уровне в папке. И все это в алфавитном порядке

2024-06-26 12:47 UTC, Lexeria commented on project/src/components/app/app.tsx
> +  films: TFilm[]
Можно и сейчас убрать, но пока можем оставить. Используется, чтобы прокинуть моки в плеер и на страницу фильма, которые, на самом деле, уже можно прокидывать не через props drilling, а с использованием нашего хранилища в самих компонентах, где они нужны

2024-06-26 12:50 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +  const genresArr = Array.from(genresSet);
Это не общепринятное сокращение, лучше писать полностью, а можно без этого. Обычно множественное число уже признак того, что это какой-то список

2024-06-26 12:52 UTC, Lexeria commented on project/src/consts/store.ts
Название файла хорошее, но для явности это больше имеет отношение к жанрам в частности или к фильмам в общем. Можно обозвать `movies.ts` и класть сюда потом всякие константы, связанные с фильмами. Но пока предлагаю просто иметь это в виду, название в целом пока подходит, над масштабируемостью и целью можно задуматься потом

2024-06-28 10:09 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +  films: TFilm[]
заменил на переменную из хранилища

2024-06-28 10:11 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +  const genresArr = Array.from(genresSet);
переименовал

2024-06-29 17:02 UTC, Lexeria requested changes

2024-06-29 17:02 UTC, Lexeria commented on project/src/components/app/app.tsx
> +type TAppProps = TMainProps
Точку с запятой забыл, но скорее отформатировать просто

2024-06-29 17:02 UTC, Lexeria commented on project/src/components/showMoreButton.tsx
> +  needHide: boolean;
Этот пропс, честно говоря не нужен, мы можем просто в нужном месте не рендерить компонент по какому-то условию, которое ты передаешь в `needHide`:
```
{!needHide && <ShowMoreButton onClickAction={...} />}
```

Только лучше отрицание не делать и упростить условие сразу в нужном ключе, мб назвав переменную с условием  `showMoreButton`, а сам компонент переименовать в `MoreButton` просто

2024-06-29 17:02 UTC, Lexeria commented on project/src/pages/main.tsx
> +  const [lengthOfSshowedFilms, setLengtOfSshowedFilms] = useState(8);
Можно попробовать назвать чуть проще в духе `shownCount`. А то сейчас еще `s` дублируется в имени, что тяжело заметить, когда оно длинное

2024-06-29 17:02 UTC, Lexeria commented on project/src/pages/main.tsx
> +    setLengtOfSshowedFilms(lengthOfSshowedFilms + 8);
Заметь, что у тебя число 8 дублируется. Это какое-то параметр, который мы можем захотеть в будущем поменять. Можно вытащить в перменную, но еще лучше утащить в файлик с константами, так как это очень похоже на неизменяемое значение, которое не хочется каждый раз объявлять

2024-06-29 17:02 UTC, Lexeria commented on project/src/pages/main.tsx
> +            onGenreChange={() => (setLengtOfSshowedFilms(8))}
Подскажешь, зачем круглые скобки после `=>`?

2024-06-29 17:02 UTC, Lexeria commented on project/src/pages/main.tsx
> +            onGenreChange={() => (setLengtOfSshowedFilms(8))}
Есть еще момент про передачу стрелочных функций, но его лучше касаться, когда дойдем до блока с оптимизацией, надеюсь не забуду

2024-06-29 17:02 UTC, Lexeria commented on project/src/pages/main.tsx
> +          <FilmList films={filmsFromStore.slice(0, lengthOfSshowedFilms)} />
Только сейчас обратил внимание на название. Почему `filmsFromStore`? `defaultFilmsList` тоже со стора ведь, думаю можно убрать лишние пару слов в названии

2024-06-29 17:02 UTC, Lexeria commented on project/src/pages/main.tsx
> +            needHide={lengthOfSshowedFilms >= filmsFromStore.length}
Вот это условие можно из пропса вытащить сюда, чтобы получился условный рендеринг. Это, кстати, частая практика, когда мы рисуем что-то условно в духе `booleanStatement && <Component />` — потому что в реакте не рендерятся всякие `null` и булевы значения, что удобно

2024-06-29 17:02 UTC, Lexeria commented on project/src/components/showMoreButton.tsx
> +  onClickAction: VoidFunction;
Можно назвать просто `onClick`, ведь это и так подразумевает за собой какое-то действие, которое совершится при клике. В обычно JS тоже есть аналогичное название, а также есть аналогичный служебный пропс при передаче обработчика в реакт-элементы, что ты и делаешь на 12-й строчке. Там без лишних слов, так что и нам нет смысла разглагольствоваться. Исключениями разве что бывают моменты, когда хотим что-то конкретизировать и дать ясности, где она нужна — как со сменой жанров: мы не хотим просто `onChange` передать, ведь так не понятно, а на какой точно `change` надо реагировать. При клике это может быть конкретика — а на что кликают? Тут у нас компонент для кнопки просто, так что вопросов не должно быть, но если элементов в компоненте больше и не понятно, то лучше добавлять ясности: `onIconClick` или `onButtonClick` например

2024-06-29 17:17 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +type TAppProps = TMainProps
добавил

2024-06-29 17:23 UTC, GoveRaven commented on project/src/components/showMoreButton.tsx
> +  needHide: boolean;
заменил

2024-06-29 17:25 UTC, GoveRaven commented on project/src/pages/main.tsx
> +  const [lengthOfSshowedFilms, setLengtOfSshowedFilms] = useState(8);
переименовал

2024-06-29 17:28 UTC, GoveRaven commented on project/src/pages/main.tsx
> +    setLengtOfSshowedFilms(lengthOfSshowedFilms + 8);
добавил константу `NUMBER_ADDED_MOVIES`

2024-06-29 17:29 UTC, GoveRaven commented on project/src/pages/main.tsx
> +            onGenreChange={() => (setLengtOfSshowedFilms(8))}
я сам не понял как добавил эти скобки. Убрал

2024-06-29 17:31 UTC, GoveRaven commented on project/src/pages/main.tsx
> +          <FilmList films={filmsFromStore.slice(0, lengthOfSshowedFilms)} />
переименовал в films

2024-06-29 17:31 UTC, GoveRaven commented on project/src/pages/main.tsx
> +            needHide={lengthOfSshowedFilms >= filmsFromStore.length}
уже заменил

2024-06-29 17:44 UTC, Lexeria commented on project/src/consts/filmList.ts
Имена должны быть в `snake-case` + можно было перименовать файлик `store.ts` в `films.ts` и туда положить две константны, относящиеся к фильмам

2024-06-29 17:48 UTC, Lexeria commented on project/src/consts/filmList.ts
> +export const NUMBER_ADDED_MOVIES = 8;
Советую использовать слово `count` вместо `number` и схожих и ставить его в конец. Added — больше про добавленные уже, стоит попробовать подобрать более логическое название, например, `DEFAULT_SHOWN_COUNT`. Оно будет, как логическое значение для init-значения в `useState` + по название подходит и к добавляемым фильмам

2024-06-29 17:49 UTC, Lexeria commented on project/src/pages/main.tsx
> +  const showButton = shownCount <= films.length;
Тут кнопка одна (но это не точно), но советую давать более логические названия, чтобы не было путаницы: `showMoreButton`, например

2024-06-29 17:50 UTC, Lexeria commented on project/src/pages/main.tsx
>    function addFilmsInList() {
Только сейчас обратил внимание на название. Мб назовем так, чтобы было чуть яснее, что за список подразумевается? Можно так и назвать например `showMoreFilms`

2024-06-29 18:06 UTC, GoveRaven commented on project/src/consts/filmList.ts
переименовал и поместил вторую константу туда

2024-06-29 18:10 UTC, GoveRaven commented on project/src/consts/filmList.ts
> +export const NUMBER_ADDED_MOVIES = 8;
переименовал

2024-06-29 18:11 UTC, GoveRaven commented on project/src/pages/main.tsx
> +  const showButton = shownCount <= films.length;
переименовал

2024-06-29 18:12 UTC, GoveRaven commented on project/src/pages/main.tsx
>    function addFilmsInList() {
переименовал

2024-06-29 18:15 UTC, Lexeria approved these changes

2024-06-29 18:19 UTC, merged