Истина где-то на сервере
GoveRaven/what-to-watch pull request #7
Opened 2024-07-05 12:04 UTC by GoveRaven

2024-07-05 12:57 UTC, Lexeria requested changes

2024-07-05 12:57 UTC, Lexeria commented on project/src/components/app/app.tsx
> +  const isFilmsLoading = useAppSelector((state) => state.isFilmsLoading);
С множественным числом используем `are` вместо `is` — загружается не один фильм, а несоклько

2024-07-05 12:57 UTC, Lexeria commented on project/src/components/films-list.tsx
>    if (match) {
Это на дискуссию, но кажется, что все же не очень хорошо, что компонент становится слишком умным и решает, какой контент показывать в зависимости от адреса — возможно, лучше тогда в нужных местах передавать нужный отфильтрованный список, который здесь останется только показать

По этой же причине ты добавляешь все больше опциональных пропсов в компонент, которые могут быть использованы только в однм месте

2024-07-05 12:57 UTC, Lexeria commented on project/src/components/films-list.tsx
> +      .filter((film) => film.genre === genre && film.name !== name)
Имя у фильмов может быть одинаковое. Советую завязываться на айдишник, как уникальное значение для каждого фильма

2024-07-05 12:57 UTC, Lexeria commented on project/src/consts/routes.tsx
> +export enum APIRoute {
Хорошо, что назвал в единственном числе. Давай `AppRoutes` тоже переименуем в единственное число — это просто соглашение о стиле

2024-07-05 12:57 UTC, Lexeria commented on project/src/index.tsx
> +import { fetchFilmAction } from './store/api-action';
У тебя есть импорт из `store` выше. Кажется, мог просто не добавить в `index.ts` файл информацию об этом файле, поэтому получился более глубокий импорт

2024-07-05 12:57 UTC, Lexeria commented on project/src/pages/movie.tsx
> +          <FilmList films={defaultFilmsList} genre={genre} name={name} />
Да, думаю выше можно завести переменную, где будет фильтрация дефолтного списка по имени и жанру, и сюда передать

2024-07-05 12:57 UTC, Lexeria commented on project/src/services/api.ts
> +const requestTimeout = 5000;
Если не ошибаюсь, то константные значения (не те, что через const объявлены, а в целом содержат общее неизменяемое значение) принято называть в `CONSTANT_CASE ` (в некоторых местах по-другому называть, можно поискать в критериях)

2024-07-05 12:57 UTC, Lexeria commented on project/src/store/actions.ts
> +export const loadFilms = createAction<TFilm[]>('data/loadFilms');
Для красоты можно отступ подставить перед этой строчкой, чтобы разделять визуально перечисления экшнов для домена `films` и для домена `data`

2024-07-05 12:57 UTC, Lexeria commented on project/src/store/api-action.ts
> +  dispatch(setFilmsLoadingStatus(true));
Тебе нужно поставить это перед тем, как ты начнешь делать запрос на сервер. Иначе эта строчка выполнится только после того, как ты получишь ответ от сервера (из-за того, что используешь await, то есть стопишь свой код, делая асинхронщину синхронной, и не идешь дальше, пока результата не будет)

2024-07-05 12:57 UTC, Lexeria commented on project/src/store/api-action.ts
> +  dispatch(loadFilms(data));
Кажется, нейминг экшна не отображает действительность — ты не загружаешь фильмы, а просто устанавливаешь их (типо `setFilms` или что-то в этом духе), загрузка уже прошла

2024-07-05 12:57 UTC, Lexeria commented on project/src/store/reducer.ts
> +  AuthStatus: AuthorizationStatus;
Почему с большой буквы?

2024-07-05 12:57 UTC, Lexeria commented on project/src/store/reducer.ts
> +  isFilmsLoading: true,
Кажется, это не совсем честно, ибо сама загрузка еще не началась, она начнется, когда обратимся к ручке для получения фильмов. А сам статус проставится в асинхронным экшне, где ты диспатчишь экншы для работы со статусом

2024-07-05 12:57 UTC, Lexeria commented on project/src/store/reducer.ts
> +        state.films = state.defaultFilmsList;
Возможно, стоит пересмотреть название, потому что это все-таки не список фильмов по умолчанию, а это в целом изначальный список после запроса на сервер. Но вариантов нейминга у меня нет, мб что-то в духе `allFilmsList`

2024-07-05 20:17 UTC, GoveRaven commented on project/src/consts/routes.tsx
> +export enum APIRoute {
а почему хорошо? Я так назвал, потому что там щас только 1 значение, и я не подумал, что добавлю ещё, значит логичнее будет назвать Routes

2024-07-05 20:19 UTC, GoveRaven commented on project/src/services/api.ts
> +const requestTimeout = 5000;
то есть называются заглавными буквами со snake_case?

2024-07-05 20:41 UTC, Lexeria commented on project/src/consts/routes.tsx
> +export enum APIRoute {
Так в критериях описано + это общая практика и стиль наименования: `Цвет какой? Красный`, а не `Цвета какие? Красный`. Поэтому правильнее `enum Color { Red = 'Red' }`, а не `enum Colors { Red = 'Red' }`

2024-07-05 20:42 UTC, Lexeria commented on project/src/services/api.ts
> +const requestTimeout = 5000;
Да, `UPPER_SNAKE_CASE`

2024-07-06 10:13 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +  const isFilmsLoading = useAppSelector((state) => state.isFilmsLoading);
заменил

2024-07-06 10:14 UTC, GoveRaven commented on project/src/consts/routes.tsx
> +export enum APIRoute {
сделал

2024-07-06 10:15 UTC, GoveRaven commented on project/src/services/api.ts
> +const requestTimeout = 5000;
заменил

2024-07-06 10:18 UTC, GoveRaven commented on project/src/store/actions.ts
> +export const loadFilms = createAction<TFilm[]>('data/loadFilms');
сделал

2024-07-06 10:19 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  dispatch(setFilmsLoadingStatus(true));
переместил

2024-07-06 10:20 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  dispatch(loadFilms(data));
заменил

2024-07-06 10:21 UTC, GoveRaven commented on project/src/store/reducer.ts
> +  AuthStatus: AuthorizationStatus;
потому что enum, а enum'ы я все с заглавной буквы называл

2024-07-06 10:24 UTC, GoveRaven commented on project/src/store/reducer.ts
> +  isFilmsLoading: true,
логично. Заменил

2024-07-06 10:26 UTC, GoveRaven commented on project/src/store/reducer.ts
> +        state.films = state.defaultFilmsList;
заменил

2024-07-06 10:53 UTC, GoveRaven commented on project/src/components/films-list.tsx
>    if (match) {
сделал компонент менее умным

2024-07-06 10:54 UTC, GoveRaven commented on project/src/components/films-list.tsx
> +      .filter((film) => film.genre === genre && film.name !== name)
заменил проверку имени на проверку id

2024-07-06 10:54 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +          <FilmList films={defaultFilmsList} genre={genre} name={name} />
добавил переменную с фильтрованным списком

2024-07-06 12:01 UTC, Lexeria commented on project/src/store/reducer.ts
> +  AuthStatus: AuthorizationStatus;
Да, но это не `enum`, это просто переменная/пропс, в котором будет храниться **значение** `enum'a`, но не сам `enum`. А если вдруг тебе понадобилось бы передать целый `enum`, то обычно его где-то объявляют, с большой буквы, и импортируют, но не передают в качестве пропсов — по крайней мере не помню таких моментов, где это пригодилось бы

2024-07-06 12:04 UTC, Lexeria commented on project/src/pages/movie.tsx
> +    id: movieId,
Если не ошибаюсь, то у тебя айди на 27-й строчке, или они разные?

2024-07-06 12:18 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +    id: movieId,
да, но там id из хука useParams

2024-07-06 12:19 UTC, GoveRaven commented on project/src/store/reducer.ts
> +  AuthStatus: AuthorizationStatus;
а, ты про поле в состоянии. Я на значение смотрю. Да, тогда ошибся

2024-07-06 12:31 UTC, Lexeria commented on project/src/pages/movie.tsx
> +    id: movieId,
Но оне ведь такой же, не? Пропс `film` пропадет, так как ты будешь получать данные о фильме потом с сервера, а `id` в браузерной строчке, как раз должен матчиться с айдишником фильма, ведь это его айдишник, для которого и отдельная страничка существует

2024-07-06 13:49 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +    id: movieId,
да, ты прав. Переделал

2024-07-08 19:12 UTC, Lexeria requested changes

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/app/app.tsx
> +    <HistoryRouter history={browserHistory}>
Если интересно, как сейчас делают роутинг, то можешь заглянуть в [доку react router'a](https://reactrouter.com/en/main/start/tutorial). В рабочих проектах все еще есть легаси, а значит ты, вероятно, встретишь и текущий способ, но знать актуальные методы тоже неплохо бы)

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/history-routes/history-routes.tsx
> +  useLayoutEffect(() => history.listen(setState), [history]);
Очень сложный вопрос, можешь не отвечать: но ты знаешь отличие хука `useEffect` от `useLayoutEffect`?

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/history-routes/history-routes.tsx
> +export default HistoryRouter;
У тебя в проекте получается смешание стилей экспортов. Давай все же будет делать именнованные экспорты, без `default`

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/logo.tsx
> +        className={`logo__link ${needClass ? 'logo__link--light' : ''}`}
Тут есть момент с лишним пробелом, но не страшно

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/logo.tsx
> +  needClass?: boolean;
Не совсем очевидное название. Давай может определим условие или обзовем, что за класс и стили идут вместе с ним. Я так понимаю, по названию класса, что это просто `light` версия. Мб что-то в духе: `isLightVersion`? Или что там по стилям меняется?

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/private-route.tsx
> +  return authStatus === AuthorizationStatus.Auth ? (
Неплохо бы отступ добавить для читаемости, но это так, на будущее: без "воздуха" код в кашу превращается и тяжело отслеживать, на какой строчке, что происходит. Поэтому нормально группировать строчки кода логической группой и отделять их пустыми строчками

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/user-block.tsx
> +  }
Три небольших моментика
1. тут очепятка, нужно `click`, видим
2. Обычно называют, используя либо `handle + название объекта + название события` (как `handleInputClick`), либо `on + (название объекта) + название события + handler` (как `on(Input)ClickHandler` — круглые скобки значат, что это не обязательно). Но надо бы поискать, как правильно действительно обзывать это дело, в твое случае достаточно `onButtonClick`
3. у нас есть специальный типизированный хук `useAppDispatch`, который возвращает диспатчер для использования. Напрямую обращаться к стору не очень хорошая практика. Так можно, но в исключительных случаях, когда это действительно необходимо

2024-07-08 19:12 UTC, Lexeria commented on project/src/components/user-block.tsx
> +  } else {
Если есть `return` внутри `if`, то `else` не нужен

2024-07-08 19:12 UTC, Lexeria commented on project/src/pages/sign-in.tsx
> +  const passwordRef = useRef<HTMLInputElement>(null);
Не критично, ибо видно по типу, но обычно `ref` называют по элементу, на который его вешают, если их несколько. В нашем случае это `input`. Как вариант, можно было назвать `emailInputRef`, но просто имей в виду

2024-07-08 19:12 UTC, Lexeria commented on project/src/pages/sign-in.tsx
> +    event.preventDefault();
Вспомнил, что с `preventDefault` не должны сработать проверки на `required`. Или они на другое событие реагируют... Как сейчас форма себя ведет?

2024-07-08 19:12 UTC, Lexeria commented on project/src/pages/sign-in.tsx
> +    event.preventDefault();
Советую поставить `preventDefault` в начало, так как обычно его ставят там, показывая, что отменяют стандартное поведение ивента и потом делают что-то свое

2024-07-08 19:12 UTC, Lexeria commented on project/src/pages/sign-in.tsx
> +      store.dispatch(authLogin({ email, password }));
Тут аналогичное замечание про `dispatch`, взятый напрямую из стора

2024-07-08 19:12 UTC, Lexeria commented on project/src/pages/sign-in.tsx
> +  function submitHandler(event: FormEvent) {
Аналогичный момент про нейминг с использованием слова `handler`

2024-07-08 19:12 UTC, Lexeria commented on project/src/services/middleware.ts
> +    if (action.type === 'route/redirectToRoute') {
Какая-то захардкоженная проверка, мб вытащить в константу или попробовать вытащить название `action'a` через обращение к переменной, куда его записываем? Не помню можно ли так

2024-07-08 19:12 UTC, Lexeria commented on project/src/store/api-action.ts
> +  }
Тип дублируется везде, не надумал вынести?

2024-07-08 19:12 UTC, Lexeria commented on project/src/store/api-action.ts
> +    await api.get<TUser>(APIRoute.Login);
Не критично, но можно убрать дженерик — он нужен для типизации получаемых данных, а мы их тут никуда не записываем, поэтому пофиг, что за тип

2024-07-08 19:12 UTC, Lexeria commented on project/src/store/api-action.ts
> +  await api.delete<TUser>(APIRoute.logout);
Тут аналогично про типизацию момент, возможно, там даже не `TUser` возвращается, ибо не знаю, зачем там его возвращать

2024-07-09 09:02 UTC, GoveRaven commented on project/src/components/history-routes/history-routes.tsx
> +  useLayoutEffect(() => history.listen(setState), [history]);
честно, я даже не знаю этот хук. Эта часть кода я взял с гитхаба react-router, которая находится тестовом виде. А сам history-routes там ещё не реализован

2024-07-09 09:05 UTC, GoveRaven commented on project/src/components/logo.tsx
> +        className={`logo__link ${needClass ? 'logo__link--light' : ''}`}
я специально поставил тот пробел, но щас понял что его можно поставить перед вторым классом. Исправил

2024-07-09 09:08 UTC, GoveRaven commented on project/src/components/logo.tsx
> +  needClass?: boolean;
логично. Заменил

2024-07-09 09:09 UTC, GoveRaven commented on project/src/components/private-route.tsx
> +  return authStatus === AuthorizationStatus.Auth ? (
понял. Исправил

2024-07-09 09:14 UTC, GoveRaven commented on project/src/components/user-block.tsx
> +  }
я что-то забыл про useAppDispatch. Как-то не красиво. Всё исправил

2024-07-09 09:17 UTC, GoveRaven commented on project/src/components/user-block.tsx
> +  } else {
сделал

2024-07-09 09:18 UTC, GoveRaven commented on project/src/pages/sign-in.tsx
> +  const passwordRef = useRef<HTMLInputElement>(null);
переименовал

2024-07-09 09:19 UTC, GoveRaven commented on project/src/pages/sign-in.tsx
> +    event.preventDefault();
Проверка на required работает с preventDefault

2024-07-09 09:23 UTC, GoveRaven commented on project/src/pages/sign-in.tsx
> +      store.dispatch(authLogin({ email, password }));
заменил

2024-07-09 09:24 UTC, GoveRaven commented on project/src/pages/sign-in.tsx
> +  function submitHandler(event: FormEvent) {
переименовал

2024-07-09 09:27 UTC, GoveRaven commented on project/src/services/middleware.ts
> +    if (action.type === 'route/redirectToRoute') {
я тоже об этом думал, но почему-то забыл исправить. Исправил

2024-07-09 09:33 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  }
заменил

2024-07-09 09:34 UTC, GoveRaven commented on project/src/store/api-action.ts
> +    await api.get<TUser>(APIRoute.Login);
убрал

2024-07-09 09:34 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  await api.delete<TUser>(APIRoute.logout);
сделал

2024-07-09 09:35 UTC, GoveRaven commented on project/src/components/history-routes/history-routes.tsx
> +export default HistoryRouter;
убрал

2024-07-09 09:41 UTC, Lexeria commented on project/src/components/history-routes/history-routes.tsx
> +  useLayoutEffect(() => history.listen(setState), [history]);
Не понял, что не смог импортировать. Мб версия роутера другая установлена

А про хуки советую почитать, потому что это базовые хуки, как `useRef` и `useState`

2024-07-09 09:47 UTC, Lexeria commented on project/src/store/actions.ts
> +export const REDIRECT_ACTION = 'route/redirectToRoute';
Можно было не создавать эту константу, так как можно просто обратиться и получить имя типа так `redirectToRoute.type`

2024-07-10 06:44 UTC, GoveRaven commented on project/src/store/actions.ts
> +export const REDIRECT_ACTION = 'route/redirectToRoute';
не подумал, что так можно. Заменил

2024-07-10 10:26 UTC, Lexeria requested changes

2024-07-10 10:26 UTC, Lexeria commented on project/src/services/api.ts
> +        toast.warn(detailMessage.error);
Решил завести переменную `detailMessage`, но в ней самой не совсем хранится `message`, а объект, у которого ты тут обращаешься к поле `data`. Мб убрать ее или хотя бы то сообщение в переменную докинуть?

2024-07-10 19:28 UTC, GoveRaven commented on project/src/services/api.ts
> +        toast.warn(detailMessage.error);
сделал

2024-07-10 22:58 UTC, Lexeria requested changes

2024-07-10 22:58 UTC, Lexeria commented on project/src/components/app/app.tsx
> +              <AddReview film={allFilmsList[0]} />
Потом уберешь, но подсвечу, что тут тоже из браузера айдишника вытаскивается просто и сам фильм

2024-07-10 22:58 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +                  <Link to={AppRoute.AddReview} className="breadcrumbs__link">
Тут не просто `AddReview` скорее всего, это же ревью для конкретного фильма, вроде, не?

2024-07-10 22:58 UTC, Lexeria commented on project/src/store/actions.ts
> +export const setSingleFilm = createAction<TFilm>('data/setSingleFilm');
`singleFilm` немного неочевидное название, но вариантов получше пока предложить не могу

2024-07-10 22:58 UTC, Lexeria commented on project/src/store/api-action.ts
> +    const response = await api.get(`${APIRoute.Films}/${filmId}`);
Напомню, что у нас есть тулза, которая отлично подменяет параметры. У нас есть роут `Film`, где можно заиспользовать `filmId`. Просто, если вдруг поменяется маршрут, тут он будет захардкожен и получится ошибка

2024-07-10 22:58 UTC, Lexeria commented on project/src/store/api-action.ts
> +    const response = await api.get(`${APIRoute.Films}/${filmId}`);
Выше ты деструктуризируешь дату, а тут решил так сделать. Мб сделаем в едином стиле?

2024-07-10 22:58 UTC, Lexeria commented on project/src/components/film-card.tsx
> +      onClick={() => navigate(to)}
Мб нижу тогда убрать ссылку, раз мы теперь у нас клик по всей карточке?

2024-07-10 22:58 UTC, Lexeria commented on project/src/store/reducer.ts
>        state.allFilmsList = action.payload;
Я уже и забыл, а чем отличается `filmsList` от `allFilmsList`? Мб переименуем их, чтобы было проще различать?

2024-07-10 22:58 UTC, Lexeria commented on project/src/store/reducer.ts
> +      state.filmsList = action.payload;
2 момента:
1. ты переименовал, но в типах все еще есть только `films`. Интересно, почему тс не ругался и не смущало ли, что автокомплита не было?
2. `films` достаточное название, чтобы понять, что это список, поэтому слово `list` избыточно, как и в `allFilmsList`

2024-07-10 22:58 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  }, [dispatch, id]);
По идее не должно, но можно проверить, что `dispatch` и `id` точно не меняются и `useEffect` вызывается единожды.

2024-07-10 22:58 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  const allFilmsList = useAppSelector((state) => state.allFilmsList);
Советую вытащить их повыше useEffect'a, чтобы были сначала хуки попроще и отвечающие за состояние, а потом за работу со всякими сайдэффектами и прочие в несколько строк кода, как `useEffect`

2024-07-10 22:58 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  if (!film || film.id !== Number(id)) {
Это хак, от которого стоит избавиться и завязываться на состояние загрузки фильмов, что более желаемое к кейсу с лоадером. `areAllFilmsLoading || isSingleFilmLoading`

2024-07-11 19:10 UTC, GoveRaven commented on project/src/pages/add-review.tsx
> +                  <Link to={AppRoute.AddReview} className="breadcrumbs__link">
исправил

2024-07-11 19:13 UTC, GoveRaven commented on project/src/components/film-card.tsx
> +      onClick={() => navigate(to)}
Я это хотел обсудить. На что заменить? На обычный `p`? Тогда при наведении курсор будет становиться кареткой, а это не очень красиво

2024-07-11 19:14 UTC, GoveRaven commented on project/src/store/reducer.ts
>        state.allFilmsList = action.payload;
переименовал

2024-07-11 19:15 UTC, GoveRaven commented on project/src/store/reducer.ts
> +      state.filmsList = action.payload;
переименовал

2024-07-11 19:16 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  }, [dispatch, id]);
без `[dispatch, id]` запускается бесконечный запрос на сервер

2024-07-11 19:17 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  const allFilmsList = useAppSelector((state) => state.allFilmsList);
переместил

2024-07-11 19:29 UTC, Lexeria commented on project/src/components/film-card.tsx
> +      onClick={() => navigate(to)}
Можно просто `span`, нам тут не так важна семантика. `p` можно, но нам нужно будет поменять стиль курсора с каретки на дефолтный и лишние отступы убрать

2024-07-11 19:30 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  }, [dispatch, id]);
Потому что второй аргумент должен быть всегда, хотя бы в виде пустого массива. Если его не будет, то `useEffect` будет вызываться на каждый рендер, что равносильно тому, что написать это без него

2024-07-11 19:33 UTC, Lexeria requested changes

2024-07-11 19:33 UTC, Lexeria commented on project/src/store/reducer.ts
> +  filmsByGenre: TFilm[];
Можно конкретизировать «filmsByCurrentGenre», но не обязательно, можно оставить так, просто не понятно из названия сейчас, на какой именно жанр они опираются

2024-07-11 19:53 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  if (!film || film.id !== Number(id)) {
заменил

2024-07-11 19:55 UTC, GoveRaven commented on project/src/components/film-card.tsx
> +      onClick={() => navigate(to)}
сделал

2024-07-11 19:57 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  }, [dispatch, id]);
Но иначе там предупреждение
![image](https://github.com/GoveRaven/what-to-watch/assets/123263785/0d17ef48-9e38-41de-8a07-2628d29580bf)
![image](https://github.com/GoveRaven/what-to-watch/assets/123263785/6d2f0fa2-34ef-4b8d-99bb-14395d4975cc)

2024-07-11 19:57 UTC, GoveRaven commented on project/src/store/reducer.ts
> +  filmsByGenre: TFilm[];
переименовал

2024-07-11 20:01 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  }, [dispatch, id]);
Это как временный эксперимент, чтоб проверить, что на самом деле `dispatch` и `id` не меняются и не триггерят `useEffect` и во всем виноват лишь строгий режим)

А про предупреждение — это нормально, но это не ошибка. Мы можем в зависимостях указывать не все, если мы в этом уверены. Поэтому стоит понять, как работает этот хук, чтобы понимать, что стоит указывать в нем, а что можно опустить и игнорировать предупреждение

2024-07-12 08:11 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  }, [dispatch, id]);
понял. Убрал

2024-07-12 08:16 UTC, GoveRaven commented on project/src/store/api-action.ts
> +    const response = await api.get(`${APIRoute.Films}/${filmId}`);
сделал

2024-07-12 15:38 UTC, GoveRaven commented on project/src/store/api-action.ts
> +    const response = await api.get(`${APIRoute.Films}/${filmId}`);
заменил

2024-07-13 09:53 UTC, Lexeria requested changes

2024-07-13 09:53 UTC, Lexeria commented on project/src/components/tabs/details.tsx
> +  const film = useAppSelector((state) => state.singleFilm);
Придумал как переименовать — `currentFilm` или `chosenFilm`

2024-07-13 09:53 UTC, Lexeria commented on project/src/components/tabs/details.tsx
> +  const { director, starring, runTime, genre, released } = film as TFilm;
Чтобы не делать приведение, можно выше проверить на `null`:
```
if (!film) {
    return null;
}
```

Либо эту проверку сделать в компоненте в файле `tabs.tsx`, а в табы прокидывать пропсы, как и раньше, чтобы эту проверку в каждом табе не дублировать

2024-07-13 09:53 UTC, Lexeria commented on project/src/components/tabs/overview.tsx
> +  }
Можно вытащить в функцию чуть выше за компонент, что-то из серии `getRatingLabel`. А чтобы не манипулировать переменной каждой раз, можно в каждом `case` делать `return` сразу

2024-07-13 09:53 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  const reviews = useAppSelector((state) => state.filmComments);
Лучше добавить немного конкретики по типу `currentFilmComments` или `chosenFilmComments`

2024-07-13 09:53 UTC, Lexeria commented on project/src/index.tsx
> +store.dispatch(fetchPromoFilm());
Возможно, запрашивать этот фильм стоит только на главной

2024-07-13 09:53 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +  if (!film) {
Лоадер не должен зависить от значений данных. Потому что отсутствие данных !== загрузка. Для этого используем вспомогательные переменный из серии `isLoading`

2024-07-13 09:53 UTC, Lexeria commented on project/src/pages/main.tsx
> +  if (!promo) {
Деструктуризация? Она у тебя ниже, а тут опять-таки нужно завязываться на флаг `isLoading` какой-нибудь, а не на отсутствие данных. А так ниже перед деструктуризацией можно делать проверку на `null` просто:
```
if (!promo) {
    return null;
}
```

Правда, возможно, не `null`, а придумать какую-то заглушку, если не будет его. Возможно, в дизайне или где-то отрисовано, что делать, если нет промо-фильма. Если не, можем сами придумать: например, брать первый фильм из списка всех фильмов в качестве промо

2024-07-13 09:53 UTC, Lexeria commented on project/src/pages/movie.tsx
> +    dispatch(fetchFilmComment(Number(id)));
`Number(id)` можно вытащить в переменную, как вариант, чтобы не дублировать преобразование каждый раз

2024-07-13 09:53 UTC, Lexeria commented on project/src/pages/movie.tsx
> +        style={{ backgroundColor: backgroundColor }}
Можно убрать `: backgroundColor`, так как название свойства совпадает с названием переменной. А можешь напомнишь, почему тут бэкграунд, причем в виде инлайн-стилей?

2024-07-13 09:53 UTC, Lexeria commented on project/src/pages/movie.tsx
> +              .slice(0, 4)}
Не советую делать такие преобразования в пропсах. Лучше вытащить в переменную выше и там заниматься этой манипуляцией

2024-07-13 09:53 UTC, Lexeria commented on project/src/store/actions.ts
> +export const setFilmComments = createAction<TReview[]>('data/setFilmComments');
У тебя группа с доменом `data` расположена выше, может перетащить эту строчку туда?

2024-07-13 09:53 UTC, Lexeria commented on project/src/store/api-action.ts
> +  try {
Если тут используешь `try-finally`, не нужно подобное делать и для `fetchFilmList` и где-то в других местах, где есть `isLoading` статус или запросы могут упасть с ошибкой. Или тут исключительный случай какой-то?

2024-07-13 09:53 UTC, Lexeria commented on project/src/store/api-action.ts
> +);
На всякий подсвечу, что тут нет `isLoading` статуса, а не факт, что эти запросы успеют выполниться к моменту, когда мы захотим отобразить их данные

2024-07-13 11:34 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +              <AddReview film={allFilmsList[0]} />
убрал

2024-07-13 11:37 UTC, GoveRaven commented on project/src/components/tabs/details.tsx
> +  const film = useAppSelector((state) => state.singleFilm);
заменил

2024-07-13 11:55 UTC, GoveRaven commented on project/src/components/tabs/details.tsx
> +  const { director, starring, runTime, genre, released } = film as TFilm;
сделал

2024-07-13 12:00 UTC, GoveRaven commented on project/src/components/tabs/overview.tsx
> +  }
сделал

2024-07-13 12:02 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  const reviews = useAppSelector((state) => state.filmComments);
сделал

2024-07-13 12:03 UTC, GoveRaven commented on project/src/index.tsx
> +store.dispatch(fetchPromoFilm());
я вот хотел с тобой это обсудить. Изначально я запрашивал только на главной, но там начинался бесконечный цикл запросов на сервер

2024-07-13 12:08 UTC, GoveRaven commented on project/src/pages/add-review.tsx
> +  if (!film) {
я хотел это тоже обсудить. Я это вписал, т.к. переменная может быть типа TFilm | null. Из-за того, что могло вернуться null, я не мог вставить некоторые элементы на страницу. Поэтому я написал это как временную меру

2024-07-13 12:10 UTC, GoveRaven commented on project/src/pages/main.tsx
> +  if (!promo) {
тут та же проблема с типами TFilm | null, которую я описал выше. Также написал это в качестве временной меры

2024-07-13 12:12 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +    dispatch(fetchFilmComment(Number(id)));
сделал

2024-07-13 12:14 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +        style={{ backgroundColor: backgroundColor }}
в объекте фильма есть свойство background, которое нигде не прописано зачем оно, но хорошо подходит под фон на странице с фильмом. Поэтому я подумал, что его там и надо использовать.
`: backgroundColor` убрал

2024-07-13 12:16 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +              .slice(0, 4)}
вынес

2024-07-13 12:22 UTC, GoveRaven commented on project/src/store/actions.ts
> +export const setFilmComments = createAction<TReview[]>('data/setFilmComments');
переместил

2024-07-13 12:24 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  try {
Тут не особенный случай. Я не заметил ещё одну функцию, где нужно также сделать.
Суть в том, что если произойдёт ошибка, то надо поставить, что загрузка завершилась. Если загрузка завершится, а фильма всё ещё нет, то нужно выводить страницу 404. Если загрузка не завершена и фильм нет, то нужно показывать загрузку

2024-07-13 16:43 UTC, Lexeria commented on project/src/index.tsx
> +store.dispatch(fetchPromoFilm());
Тут надо смотреть, как ты запрашиваешь. Пока сложно сказать, почему там бесконечный цикл, поэтому ничего подсказать не могу

2024-07-13 16:45 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +  if (!film) {
Это отдельный кейс все-таки: `null` — не гарантия того, что идет запрос. Ты можешь сначала по `isLoading` флагу рисовать лоадер, потом ниже проверять условие на `null` и возвращать `null` в случае, если почему-то так случилось, а потом возвращать норм компонент с нужными данными:
```
if (isLoading) {
    return <Loader />;
}

if (!film) {
   return null;
}

return <NormComponent />;
```

2024-07-13 16:45 UTC, Lexeria commented on project/src/pages/main.tsx
> +  if (!promo) {
Предложил вверху, как это можно учесть

2024-07-13 16:47 UTC, Lexeria commented on project/src/store/api-action.ts
> +  try {
Не, нормально, я просто хотел, чтобы ты пробежался глазами по другими асинхронным экшнам и проверил, что везде есть `try-(catch)-finally`, где это нужно. Мб есть еще случай, где запрос может упасть, а мы забудем `isLoading` переключить из-за этого

2024-07-13 17:10 UTC, Lexeria requested changes

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/rating-input.tsx
> +  ratingHandler: (event: ChangeEvent<HTMLInputElement>) => void;
Надо поискать коммент, где я писал, как правильно обзывать переменные, но если вкратце, то обычно это просто `on + (на каком элементе событие происходит) + (тип события)` (к примеру `onButtonClick`). Аналогично для этого кейса мы можем назвать `onRatingChange`

Со словом `handler` мы тоже можем обзывать обработчики, но тогда нужно пояснять хотя бы, к чему они: `handleRatingChange` или со словом `handler` в конце — но это обычно история про классы или функции, объявленные внутри, но не про пропсы

Нашел страую статью, но можно погуглить что-то посвежее по схожим словам из ссылки: https://jaketrent.com/post/naming-event-handlers-react/

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/rating-input.tsx
> +  const rates = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1];
Ты каждый раз объявляешь этот массив, советую вытащить за компоненту, потому что он не меняется

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/rating-input.tsx
> +type TRatingInput = {
Для типов пропсов обычно добавляют ключевое слово `Props` в конце

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  const needDisabledButton = text.length < 50 || text.length > 400;
`Disable`, а не `Disabled` — потому что ты подразумеваешь, какое-то действие, а не состояния. Для состояния можно назвать так `isButtonDisabled`

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/rating-input.tsx
> +  ratingHandler: (event: ChangeEvent<HTMLInputElement>) => void;
Можно упростить тип функции, передавая вместо `event` сразу нужный `rating` в виде строки

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/review-form.tsx
> +              disabled={needDisabledButton || !rating}
`|| !rating` можно утощить в переменную, чтобы условие для блокирования кнопки менялось в одном месте, а тут мы не пытались его расширить и нагромождать

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/reviews-column.tsx
> +type TReviews = {
Потерял суффикс `Props` в конце, хотя раньше он был

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/overview.tsx
> +type TOverview = {
Потерял суффикс `Props` в конце

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/details.tsx
> +type TDetails = {
Потерял суффикс `Props` в конце

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  const chosenFilmsComments = useAppSelector((state) => state.filmComments);
`Film`, наверное, если у нас речь про один фильм

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  const isFilmCommentLoading = useAppSelector(
`AreFilmCommentsLoading`, если речь про несколько комментов

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  } else if (!isFilmCommentLoading && !chosenFilmsComments) {
Когда у нас есть `return` в блоке `if`, не нужно писать `else` — можно сразу писать новый `if` или просто `return`, если условия нет

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  } else if (!isFilmCommentLoading && !chosenFilmsComments) {
А еще можно вот так:
```
if (!chosenFilmsComments) {
    return areFilmCommentsLoading ? <Loader /> : <NotFound />;
}
```

2024-07-13 17:10 UTC, Lexeria commented on project/src/components/tabs/tabs.tsx
>    return (
Перед `return` хорошо бы один оступ делать, если есть еще какие-то строчки помимо него. Просто для красоты и читаемости

2024-07-13 17:10 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +    return <NotFound />;
Тут аналогично: стоит убрать `else` или переписать:
```
if (!film) {
    return isFilmLoading ? ... : ...;
}
```

2024-07-13 17:10 UTC, Lexeria commented on project/src/pages/add-review.tsx
> +    return <NotFound />;
Но лучше все же так:
```
if (isFilmLoading) {
    return <Loader />;
}

if (!film) {
    return <NotFound />;
}
```

Так выглядит логичнее — если уже нет запроса, но и фильма нет, то отображем, что ничего не найдено

2024-07-13 17:10 UTC, Lexeria commented on project/src/pages/main.tsx
>    }
Не буду дублировать, но аналогично замечание, как в `add-review.tsx` выше

2024-07-14 10:04 UTC, GoveRaven commented on project/src/components/rating-input.tsx
> +  const rates = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1];
сделал

2024-07-14 10:04 UTC, GoveRaven commented on project/src/components/rating-input.tsx
> +type TRatingInput = {
переименовал

2024-07-14 10:05 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +  const needDisabledButton = text.length < 50 || text.length > 400;
переименовал

2024-07-14 10:07 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +              disabled={needDisabledButton || !rating}
переместил условие

2024-07-14 10:08 UTC, GoveRaven commented on project/src/components/tabs/reviews-column.tsx
> +type TReviews = {
переименовал

2024-07-14 10:09 UTC, GoveRaven commented on project/src/components/tabs/overview.tsx
> +type TOverview = {
добавил

2024-07-14 10:09 UTC, GoveRaven commented on project/src/components/tabs/details.tsx
> +type TDetails = {
добавил

2024-07-14 10:10 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  const chosenFilmsComments = useAppSelector((state) => state.filmComments);
переименовал

2024-07-14 10:10 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  const isFilmCommentLoading = useAppSelector(
переименовал

2024-07-14 10:12 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  } else if (!isFilmCommentLoading && !chosenFilmsComments) {
очень умное условие с тернарным оператором. Сначала и не понял. Переписал

2024-07-14 10:13 UTC, GoveRaven commented on project/src/components/tabs/tabs.tsx
>    return (
добавил отступ

2024-07-14 10:15 UTC, GoveRaven commented on project/src/pages/add-review.tsx
> +    return <NotFound />;
переписал

2024-07-14 10:16 UTC, GoveRaven commented on project/src/pages/main.tsx
>    }
переписал

2024-07-14 10:27 UTC, GoveRaven commented on project/src/components/rating-input.tsx
> +  ratingHandler: (event: ChangeEvent<HTMLInputElement>) => void;
передать rating вместо event не получилось
![image](https://github.com/user-attachments/assets/df79096d-6fb1-462d-a20d-4fd47b0e20ce)
![image](https://github.com/user-attachments/assets/224e4f23-498c-495d-9a6b-eb5066730fe2)

2024-07-14 10:30 UTC, GoveRaven commented on project/src/pages/add-review.tsx
> +  if (!film) {
переписал

2024-07-14 10:30 UTC, GoveRaven commented on project/src/pages/main.tsx
> +  if (!promo) {
переписал

2024-07-14 10:31 UTC, GoveRaven commented on project/src/store/api-action.ts
> +);
добавил

2024-07-14 15:03 UTC, Lexeria commented on project/src/components/rating-input.tsx
> +  ratingHandler: (event: ChangeEvent<HTMLInputElement>) => void;
Как в тг написал, недостаточно поменять тип — нужно, чтобы и функция и ее использование стали соответствовать типу. Просто нет смысла писать сложный тип, мы можем его упростить, сделать более гибким и универсальным, просто в местах упоминания и использования сделать доп манипуляции, чтобы соответствовать новому типу

2024-07-14 15:08 UTC, Lexeria requested changes

2024-07-14 15:08 UTC, Lexeria commented on project/src/components/rating-input.tsx
> +  handlerInputChange: (event: ChangeEvent<HTMLInputElement>) => void;
Нейминн все еще не тот. `Handler` — слово в конце, в начале без буквы `r` просто `handle`. Но нейминг пропсов обычно через `on` начинается. Попробуй прочитать тот коммент еще раз и пробежаться по статье, что я кидал

2024-07-14 15:08 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  const needDisableButton = text.length < 50 || text.length > 400 || !rating;
Тут все-таки лучше через `is` как `isButtonDisabled`. Потому что `need` обычно подразумевает, что следом пойдет действие, которое заблокирует кнопку

2024-07-15 15:58 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +  const needDisableButton = text.length < 50 || text.length > 400 || !rating;
переименовал

2024-07-15 15:58 UTC, GoveRaven commented on project/src/components/rating-input.tsx
> +  handlerInputChange: (event: ChangeEvent<HTMLInputElement>) => void;
переименовал

2024-07-15 15:58 UTC, GoveRaven commented on project/src/components/rating-input.tsx
> +  ratingHandler: (event: ChangeEvent<HTMLInputElement>) => void;
переписал в `event: { target: { value: string } }`. Жду реакции

2024-07-16 15:05 UTC, GoveRaven commented on project/src/components/rating-input.tsx
> +  ratingHandler: (event: ChangeEvent<HTMLInputElement>) => void;
переписал в тип без ивента

2024-07-17 08:07 UTC, Lexeria requested changes

2024-07-17 08:07 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  function handlerInputChange(ratingArg: string) {
Можно обозвать хотя бы `chosenRating`, потому что это и так `arg`, нет смысла добавлять этот суффикс

2024-07-17 08:07 UTC, Lexeria commented on project/src/components/private-route.tsx
> +  }
В принципе, можно оставить и так. Я просто видел, что у тебя было какое-то действие для сохранения статуса авторизации, но мб показалось

2024-07-18 09:56 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +  function handlerInputChange(ratingArg: string) {
переименовал

2024-07-18 14:05 UTC, Lexeria approved these changes

2024-07-20 10:56 UTC, merged