Оптимизируй это
GoveRaven/what-to-watch pull request #8
Opened 2024-08-02 10:52 UTC by GoveRaven

2024-08-02 11:25 UTC, Lexeria requested changes

2024-08-02 11:25 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  const filmId = Number(id);
Не критично, но эту переменную можно объявить внутри `handelFormSumbit`, чтобы лишний раз не преобразовать айдишник в число при перерендерах `filmId` до отправки

2024-08-02 11:25 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  function handelFormSumbit(event: FormEvent) {
Очепятка закралась: `handle`*
И советую все же прочитать про нейминг ту ссылку, что я оставлял. И в случае непоняток прийти в личку и обсудить, потому что тут все же лучше `onSubmit` просто обозвать функцию

2024-08-02 11:25 UTC, Lexeria commented on project/src/components/review-form.tsx
>    function handlerInputChange(chosenRating: string) {
Видимо, в прошлые разы не заметил и не подсветил: правильнее `handle`. Потому что глагол в начале, а `handler` — существительное, которое принято в конец ставить: `inputChangeHandler` будет звучать лучше, если хочется использоваться именно `handler`

2024-08-02 11:25 UTC, Lexeria commented on project/src/components/review-form.tsx
> +      postComment({ comment: text, rating: Number(rating), id: filmId })
Мб тогда переменную переименовать в `comment`, а не `text`? Будет более узконаправленное название, означающее, что за текст у нас хранится в стейте

2024-08-02 11:25 UTC, Lexeria commented on project/src/components/review-form.tsx
> +      postComment({ comment: text, rating: Number(rating), id: filmId })
Интересно, почему для `id` преобразование с помощью `Number` вынесено в переменную и объявлено выше, а `rating` без переменной и сразу на месте преобразуется

2024-08-02 11:25 UTC, Lexeria commented on project/src/components/user-block.tsx
> +  const avatar = useAppSelector((state) => state.user?.avatarUrl);
Советую добавить в название переменной хотя бы слово `Url` или `Src` в конце, потому что иначе более широкое название без понимания типа и хранимого значения получается сейчас

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/actions.ts
> +export const redirectToRoute = createAction<AppRoute | string>(
Тогда лучше просто `string` сразу поставить, потому что у тебя значения `AppRoute` — строчки. А любой путь и так может быть строчкой. Хочется, конечно, более явную типизацию в рамках существующих и описанных маршрутов, как в `AppRoute`, но тут надо будет исхитриться и писать сложные типы. Лучше обойтись обычным `string` и не мучиться

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/api-action.ts
> +  { comment: string; rating: number; id?: number },
`id` по контракту — обязательное значение, мы не можем отправить комментарий к фильму без айдишника

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/api-action.ts
> +>('data/postComment', async (dataComment, { dispatch, extra: api }) => {
`data` — общее слово про любую совокупность данных в целом, лучше его не использовать и конкретизировать другими фразами/словами. Например, `addedComment`, `(added)commentMeta`, `(added)commentInfo`, ... На что фантазии хватит, `meta` — мета-информация, что-то дополнительное, побочное, не уверен, что можно сюда отнести, но можешь почитать про значение в инете и мб захочешь его заиспользовать

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/api-action.ts
> +  delete dataComment.id;
А зачем эта строчка?

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/api-action.ts
> +  const redirectApi = makePathWithParams(AppRoute.Film, { id });
Кажется, в конце забылось слово `route`. Можно просто `redirectRoute`. Сейчас ощущение, что у эта переменная хранится в себе `api`, с которым можно взаимодействовать и вызывать какие-то методы для этого `api`

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/api-action.ts
> +      const { data } = await api.get(APIRoute.Login);
Тут `data` не типизирована. Кажется, у нее значение `any`. Так легко получить какую-то ошибку в дальнейшем

2024-08-02 11:25 UTC, Lexeria commented on project/src/store/api-action.ts
> +  dispatch(setUser(data));
Не критично, но можно чуть выше поставить, как на 115 строчке: сначала добавляем инфу о юзере, потом о его статусе авторизации, чтобы после редиректа не получилось, что на мгновение не подгрузилась инфа о юзере. Но это вряд ли случится по разным причинам, как минимум, потому что сам редирек сейчас ниже находится, но чисто для единообразия и «на всякий случай»

2024-08-02 12:26 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +  function handelFormSumbit(event: FormEvent) {
Но с именованием функций как раз рекомендуют опускать `on`
![image](https://github.com/user-attachments/assets/714e5dec-c549-40d9-bfff-8dd76a45c6bc)

2024-08-02 12:29 UTC, GoveRaven commented on project/src/components/user-block.tsx
> +  const avatar = useAppSelector((state) => state.user?.avatarUrl);
переименовал

2024-08-02 12:35 UTC, GoveRaven commented on project/src/store/actions.ts
> +export const redirectToRoute = createAction<AppRoute | string>(
сделал

2024-08-02 12:36 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  delete dataComment.id;
чтоб удалить ключ `id` из передаваемого объекта и этот объект сразу передать post-запросом

2024-08-02 12:37 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  const redirectApi = makePathWithParams(AppRoute.Film, { id });
переименовал

2024-08-02 12:40 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  dispatch(setUser(data));
переместил

2024-08-02 12:41 UTC, GoveRaven commented on project/src/store/api-action.ts
> +>('data/postComment', async (dataComment, { dispatch, extra: api }) => {
переименовал

2024-08-02 12:46 UTC, GoveRaven commented on project/src/store/api-action.ts
> +      const { data } = await api.get(APIRoute.Login);
но я ни одной `data `не задавал тип

2024-08-02 12:48 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +      postComment({ comment: text, rating: Number(rating), id: filmId })
я что-то тупонул с rating и id, да. Исправил и переименовад

2024-08-02 15:41 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  function handelFormSumbit(event: FormEvent) {
Это нейминг для функций, который ты передаешл в качестве пропсов в другую функцию. Когда объявляешь функцию внутри компонента, где передаешь нужный ивент, лучше использовать нейминг с использованием on

2024-08-02 15:43 UTC, Lexeria commented on project/src/store/api-action.ts
> +  delete dataComment.id;
Советую на 102 строчке сделать махинацию тогда:
```
const { id, ...requestInfo } = dataComment;
```
И передать потом вторую переменную, без всяких delete

2024-08-02 15:44 UTC, Lexeria commented on project/src/store/api-action.ts
> +      const { data } = await api.get(APIRoute.Login);
Типизация у тебя идет через указания дженерика у метода get/post — как указания типв возвращаемого значения

2024-08-02 16:06 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +  const filmId = Number(id);
в итоге эту переменную стёр

2024-08-02 16:07 UTC, GoveRaven commented on project/src/components/review-form.tsx
>    function handlerInputChange(chosenRating: string) {
переименовал

2024-08-02 16:10 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  delete dataComment.id;
заменил

2024-08-02 16:11 UTC, GoveRaven commented on project/src/store/api-action.ts
> +      const { data } = await api.get(APIRoute.Login);
добавил

2024-08-02 16:12 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  { comment: string; rating: number; id?: number },
убрал `?`

2024-08-02 16:21 UTC, Lexeria requested changes

2024-08-02 16:21 UTC, Lexeria commented on project/src/components/review-form.tsx
> +  const [comment, setText] = useState('');
Забыл сеттер переименовать

2024-08-02 16:21 UTC, Lexeria commented on project/src/store/api-action.ts
> +  const redirectApiRoute = makePathWithParams(AppRoute.Film, { id });
Слово `api` все еще лишнее, ибо это твой редирект, а не `api`

2024-08-02 18:12 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +  const [comment, setText] = useState('');
переименовал

2024-08-02 18:58 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  const redirectApiRoute = makePathWithParams(AppRoute.Film, { id });
переименовал

2024-08-07 18:31 UTC, Lexeria requested changes

2024-08-07 18:31 UTC, Lexeria commented on project/src/components/app/app.tsx
> +  const isAuthStatusChecked = useAppSelector(getIsAuthStatusChecked);
Это касается всех селекторов, но напишу тут. Обычно принято называть селекторы, начиная с префикса `select`. Это не обязательно, но рекомендовано ребятами из редакса: https://redux.js.org/style-guide/#name-selector-functions-as-selectthing

2024-08-07 18:31 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +  });
У тебя `useEffect` без зависимостей — толку от этого нет, ибо он будет срабатывать на каждый рендер

2024-08-07 18:31 UTC, Lexeria commented on project/src/store/slices/films-slice/films-slice.ts
> +      const allFilms: TFilm[] = action.payload;
Конечно, пока все еще смущает, что список всех фильмов в другом слайсе, но пока вариантов, как это обыграть получше у меня тоже нема

2024-08-07 18:31 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  const areFilmCommentsLoading = useAppSelector(getIsFilmCommentLoading);
Названия как-то расходятся: переменная подразуемает несколько комментов, а в селекторе по названию только один будто

2024-08-07 18:31 UTC, Lexeria commented on project/src/components/user-block.tsx
> +              src={avatarUrl?.avatarUrl}
Так как он опциональный, может возникнуть проблема при загрузке картинки. Есть такое понятие, как `fallback` — что-то типа заглушки на время загрузки или проблем с загрузкой, либо дефолтное значение. Если есть желание, можешь провернуть что-то из этой серии: https://stackoverflow.com/a/980948 (либо найти другие варианты, это не единстввенный)

Либо еще проверить по тз — не указано ли чего про изображение. Мб там просто какой-то цвет должен грузиться или еще чего, если картинка не загружается

2024-08-07 18:31 UTC, Lexeria commented on project/src/consts/store-action.ts
> +export enum actionName {
Имя enum'а не поправил, я в тг про это написал, если что, можешь найти или написать мне, если не найдешь, что я писал

2024-08-07 18:31 UTC, Lexeria commented on project/src/pages/main.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
А тут точно должен быть отступ? Если да, то ладно, просто забавно, что его раньше не было

2024-08-07 18:31 UTC, Lexeria commented on project/src/store/slices/data-slice/data-slice.ts
> +  reducers: {},
А зачем указывать его, если он пустой?

2024-08-07 18:31 UTC, Lexeria commented on project/src/store/slices/data-slice/data-slice.ts
> +export const DataSlice = createSlice({
А имена слайсов с большой буквы принято называть?

2024-08-07 18:31 UTC, Lexeria commented on project/src/store/slices/films-slice/films-slice.ts
> +      const allFilms: TFilm[] = action.payload;
Все еще смущает, что он не знает ничего про список фильмов и получает его во вне. Как будто тогда теряется смысл от этого действия, если мы постоянно пичкаем в него свой список самостоятельно. Надо бы подумать, как это обыграть. Я бы пока в целом посмотрел, как принято разбивать в редаксе на слайсы — моежт там и появится разгадка на этот вопрос

2024-08-07 18:31 UTC, Lexeria commented on project/src/store/slices/user-slice/user-slice.ts
> +  reducers: {},
Тут тоже без редьюсеров

2024-08-07 18:31 UTC, Lexeria commented on project/src/store/slices/user-slice/user-slice.ts
> +      });
Не уверен, потому что не помню, зачем идейно у нас это значение, но тут не нужно `isAuthStatusChecked` поставить в `false`? Будто нет, ибо мы же проверили статус авторизации, но все же

2024-08-08 08:47 UTC, GoveRaven commented on project/src/components/app/app.tsx
> +  const isAuthStatusChecked = useAppSelector(getIsAuthStatusChecked);
переименовал

2024-08-08 08:48 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +  });
добавил

2024-08-08 08:49 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  const areFilmCommentsLoading = useAppSelector(getIsFilmCommentLoading);
переименовал

2024-08-08 08:53 UTC, GoveRaven commented on project/src/components/user-block.tsx
> +              src={avatarUrl?.avatarUrl}
я ничего не нашёл в ТЗ по поводу ошибки при загрузки аватарки, поэтому возьму аватарку, которая была в статичном примере страницы

2024-08-08 08:57 UTC, GoveRaven commented on project/src/consts/store-action.ts
> +export enum actionName {
поправил

2024-08-08 08:58 UTC, GoveRaven commented on project/src/pages/main.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
это преттир прошёлся и сделал его. Видимо нужен там

2024-08-08 08:58 UTC, GoveRaven commented on project/src/store/slices/data-slice/data-slice.ts
> +  reducers: {},
там нужен редьюсер. Если убрать ты выведет ошибку
![image](https://github.com/user-attachments/assets/12130bdb-a109-458b-bbaf-cd3161f601cb)

2024-08-08 09:01 UTC, GoveRaven commented on project/src/store/slices/data-slice/data-slice.ts
> +  reducers: {},
В документации тоже показывают, что он нужен хотя бы пустым
![image](https://github.com/user-attachments/assets/a81f055f-4ecc-470b-b372-060de912e9d5)

2024-08-08 09:04 UTC, GoveRaven commented on project/src/store/slices/data-slice/data-slice.ts
> +export const DataSlice = createSlice({
Нет, не с большой. Это я с чего-то так сам решил. Исправил

2024-08-08 09:09 UTC, GoveRaven commented on project/src/store/slices/user-slice/user-slice.ts
> +      });
Во-первых, `isAuthStatusChecked` меняется в действии `checkAuth`, которое срабатывает сразу при загрузке страницы
Во-вторых, `isAuthStatusChecked` имеет значение `false`, пока `authStatus` имеет значение `AuthorizationStatus.Unknow`. Если мы знаем какое значение у `authStatus`, то это уже нельзя считать, что мы не проверили статус авторизации, а значит статус `true`

2024-08-08 18:57 UTC, Lexeria commented on project/src/components/user-block.tsx
> +              src={avatarUrl?.avatarUrl}
Это нормас, понятно, как выглядит эта заглушка и как это работает? Ну, и что за понятие фолбэка такое?

2024-08-08 18:58 UTC, Lexeria commented on project/src/store/slices/data-slice/data-slice.ts
> +  reducers: {},
Ага, увидел, где-то видел, что опускают, видимо, ни при кейсе с `extraReducers`

2024-08-08 19:07 UTC, Lexeria requested changes

2024-08-08 19:07 UTC, Lexeria commented on project/src/components/genres-list.tsx
>    films.forEach((film) => genresSet.add(film.genre));
А какой список фильмов мы передаем сюда? `allFilms` с 21-й строчке недостаточно будет? Мб в каких-то компонентах еще остались пережитки прошлого без работы с глобальным стейтом?

2024-08-08 19:07 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +  }, [allFilms, dispatch]);
А если жанр поменялся, не нужно актуализировать? Или почему он сейчас актуализируется при смене жанра?

2024-08-08 19:07 UTC, Lexeria commented on project/src/components/user-block.tsx
> +              src={avatarUrl?.avatarUrl || 'img/avatar.jpg'}
Это если ссылка `undefined`. Если глянешь, что я тебе кидал, там история про общий кейс, когда не удалось подгрузить картинку по `src`. Учитывая, что у нас картинки хранятся на сервере, то вряд ли возможен случай, что она не загрузится, но перестраховаться все же стоит

2024-08-08 19:07 UTC, Lexeria commented on project/src/consts/store-action.ts
> +export enum ActionName {
Я в тг писал еще про то, что это на самом деле не `ActionName`, а `SliceName`. Потому что это имена для сущности «слайс», а экшн — одна из сущностей, с которым слайс работает. Как минимум, ты даешь это имя штуке, которая в себе содержит редьюсеры, а экшны у нас в себе никакие редьюсеры не содержат

2024-08-08 19:07 UTC, Lexeria commented on project/src/components/tabs/reviews.tsx
> +  const areFilmCommentsLoading = useAppSelector(selectIsFilmCommentsLoading);
Название селектора осталось через `is`, но тред ты зарезолвил. Забыл закоммитить?

2024-08-11 09:12 UTC, GoveRaven commented on project/src/components/genres-list.tsx
>    films.forEach((film) => genresSet.add(film.genre));
да, я щас увидел, что я пропс `films` - это все фильмы, как и переменная `allFilms`. Убираю

2024-08-11 09:17 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +  }, [allFilms, dispatch]);
`useEffect` вызывается при загрузке страницы, чтобы изначально актуализировать список фильмов. В дальнейшем, при нажатии на кнопку, также вызывается актуализация списка (40 строка)

2024-08-11 09:20 UTC, GoveRaven commented on project/src/components/tabs/reviews.tsx
> +  const areFilmCommentsLoading = useAppSelector(selectIsFilmCommentsLoading);
я тогда исправил имя слайса. Раньше было "Comment" - заменил на "Comments". Is в названии я не заметил

2024-08-11 10:11 UTC, Lexeria requested changes

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +  }, [allFilms, dispatch]);
При монтировании компонента скорее, ибо загрузка страницы лишь факт, почему компонент замонтировался. Может на 42 строчке убрать актуализацию списка, а тут добавить в зависимость жанр текущий. Чтобы компонент обновлялся всегда, когда меняется жанр и нам не нужно было в других местах вызывать актуализацию списка?

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +  isNeedReviewBtn?: boolean;
btn не общеприянтое сокращение, лучше так не сокращать. Можно обозвать `showAddReviewButton` или `isAddReviewVisible`

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +  const canShowReviewBtn =
Btn — не общепринятое сокращение

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +  function onBtnClick() {
Аналогично про btn. Плюс не понятно, про какую кнопку речь

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +  const [isFavoriteState, setIsFavoriteState] = useState(isFavorite);
Слово `state` излишне. Лучше переименовать пропс на `isInMyList` например, а тут убрать лишнее слово

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +      setIsFavoriteState(!isFavoriteState);
Работает без задержки сейчас?

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
А зачем это фетчить? Чтобы при заходе на вкладку с избранными фильмами были все фильмы?

2024-08-11 10:11 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +      {canShowReviewBtn ? (
Можно убрать `: null` в конце, а вместо ? поставить &&

Тернарный оператор ставит в тех местах, где у нас не JSX — в класснеймах или некоторых пропсах

2024-08-11 10:11 UTC, Lexeria commented on project/src/consts/routes.tsx
> +  favorite = '/favorite',
Почему-то у тебя некоторые с маленькой буквы, а некоторые с большой. Стоит писать в едином стиле

2024-08-11 10:11 UTC, Lexeria commented on project/src/pages/main.tsx
> +  const { isFavorite } = promo;
У тебя ниже деструктуризация promo, можно там дополнить

2024-08-11 10:11 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  const { isFavorite } = film;
У тебя ниже деструктуризация film, можно там дополнить

2024-08-11 10:11 UTC, Lexeria commented on project/src/consts/routes.tsx
> +  favorite = '/favorite',
Лучше дописать в конце films, чтобы было понятно, что именно избранное

2024-08-11 10:11 UTC, Lexeria commented on project/src/store/api-action.ts
> +  await api.post(`${apiRoute}`);
А зачем здесь шаблонная строка?

2024-08-11 10:11 UTC, Lexeria commented on project/src/store/slices/data-slice/data-slice.ts
> +      .addCase(fetchFavoriteFilms.fulfilled, (state, action) => {
А не нужен пендинг? Если зайдет на страничку с избранными фильмами, а там еще не загрузилось ничего?

2024-08-11 10:11 UTC, Lexeria commented on project/src/store/slices/data-slice/selector.ts
> +  state[SliceName.Data].isFilmCommentLoading;
А тут поле не переименовалось. Надо тоже на areFilmComments переименовать, иначе потом путаница может возникнуть

2024-08-11 19:32 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +      setIsFavoriteState(!isFavoriteState);
с задержкой. Я пока не посмотрел то, что ты скидывал для ускорения работы со стороны сервера

2024-08-11 19:33 UTC, GoveRaven commented on project/src/store/api-action.ts
> +  await api.post(`${apiRoute}`);
это я зачем-то оставил случайно. Раньше там было по другому написано

2024-08-11 19:34 UTC, GoveRaven commented on project/src/consts/store-action.ts
> +export enum ActionName {
переименовал

2024-08-11 19:36 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +  isNeedReviewBtn?: boolean;
переименовал

2024-08-11 19:37 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +  const canShowReviewBtn =
переименовал

2024-08-11 19:37 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +  function onBtnClick() {
переименовал

2024-08-11 19:39 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +  const [isFavoriteState, setIsFavoriteState] = useState(isFavorite);
переименовал

2024-08-11 19:41 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
чтобы обновлялось количество любимых фильмов, отображаемых в кнопке. Щас подумал, что можно не использовать фетч, а просто менять число

2024-08-11 19:42 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +      {canShowReviewBtn ? (
заменил

2024-08-11 19:43 UTC, GoveRaven commented on project/src/consts/routes.tsx
> +  favorite = '/favorite',
переименовал

2024-08-11 19:44 UTC, GoveRaven commented on project/src/pages/main.tsx
> +  const { isFavorite } = promo;
перенёс

2024-08-11 19:44 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  const { isFavorite } = film;
перенёс

2024-08-11 19:46 UTC, GoveRaven commented on project/src/store/slices/data-slice/data-slice.ts
> +      .addCase(fetchFavoriteFilms.fulfilled, (state, action) => {
я это не предусмотрел, но допишу этот момент

2024-08-11 19:47 UTC, GoveRaven commented on project/src/store/slices/data-slice/selector.ts
> +  state[SliceName.Data].isFilmCommentLoading;
переименовал

2024-08-18 16:19 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +      setIsFavoriteState(!isFavoriteState);
Оставлю тут тоже фразу «Optimistic UI». Запрос не будет быстрее, но можно визуально показывать будто все хорошо

2024-08-18 16:20 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
Это не совсем честно, нам нужно увеличивать число только, если запрос прошел успешно. А на страничке с избранными фильмами есть этот фетч?

2024-08-18 16:37 UTC, Lexeria requested changes

2024-08-18 16:37 UTC, Lexeria commented on project/src/pages/player.tsx
> +function culcLeftTime(runTime: number): string {
Очепятка, calc? Можно еще просто на `get` заменить

2024-08-18 16:37 UTC, Lexeria commented on project/src/pages/player.tsx
> +  if (!film) {
Вброшу про отдельное состояние для лоадеров. Отсутствие данных для нас не должно означать, что идет загрузка по нескольким причинам, две из которых в тг писал как раз

2024-08-18 16:37 UTC, Lexeria commented on project/src/pages/player.tsx
> +  }
По поводу названий:
1. `handler` в конце или `handle` в начале уместно в основном только, когда мы передаем функцию в качестве пропса другому реакт компоненту, а не реакт элементу
2. В названиях функций должны быть глаголы, потому что функции — какое-то действие. И это касается названия со словами из 1-го пункта, так и с названиями, начинающихся с `on`: `onPlayButtonClick`, `playButtonClickHandler`. Глагол — `click`. Для первых двух функций можно, конечно, сказать, что `play` и `pause` — глаголы, но ощущение, что все же подразумевались кнопки тут

2024-08-18 17:13 UTC, GoveRaven commented on project/src/pages/player.tsx
> +function culcLeftTime(runTime: number): string {
заменил

2024-08-18 17:24 UTC, GoveRaven commented on project/src/pages/player.tsx
> +  }
поменял имена

2024-08-19 16:38 UTC, Lexeria requested changes

2024-08-19 16:38 UTC, Lexeria commented on project/src/pages/player.tsx
> +  function onClickPlayButton() {
Название у этой функции и ниже должно быть другое, в стиле: «on + сущность, которая подверглась действию + действие». Сейчас это читается как «на клик, кнопка воспроизведения», а должно «на клик по кнопке воспроизведения», то есть «onPlayButtonClick»

2024-08-19 16:38 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +function actualizeFilmsList(allFilms: TFilm[], genre: string) {
Тогда не actualize, а getActualized. Потому что мы возвращаем список фильмов, а не актуализируем другой список

2024-08-20 10:42 UTC, GoveRaven commented on project/src/pages/player.tsx
> +  function onClickPlayButton() {
переименовал функции

2024-08-20 10:43 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +function actualizeFilmsList(allFilms: TFilm[], genre: string) {
переименовал

2024-08-20 10:46 UTC, GoveRaven commented on project/src/components/user-block.tsx
> +              src={avatarUrl?.avatarUrl}
Фолбэк - функция, которая вызывается если произошла ошибка при основном запросе. В нашем случае это запасной вариант аватарки, если не получится получить аватарку с сервера

2024-08-20 10:47 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +  }, [allFilms, dispatch]);
Я переписал useEffect в одном из последних коммитов и дописал там зависимость с жанром. Этот коммит можно зеловить?

2024-08-20 11:05 UTC, GoveRaven commented on project/src/pages/player.tsx
> +  if (!film) {
исправил

2024-08-20 11:05 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
теперь есть

2024-08-20 11:07 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
По поводу увеличения числа любимых фильмов только при прохождении запроса. Так ведь и происходит. Я получаю список фильмов с сервера, а если фильм есть на сервере, то и запрос прошёл

2024-08-20 11:42 UTC, Lexeria commented on project/src/components/user-block.tsx
> +              src={avatarUrl?.avatarUrl}
Фоллбэк — не обязательно функция, но в целом это история про запасной вариант, когда что-то пошло не так. Можно сказать дефолтное значение для опционального параметра

2024-08-20 11:43 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +  }, [allFilms, dispatch]);
Да, либо можем зарезолвить, когда разберемся, что за магия с этим юзЭффектом происходит и почему

2024-08-20 11:45 UTC, Lexeria commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
Это да, но кажется, что можно без запроса избранных фильмов увеличивать/уменьшать счетчик. Ведь по факту мы же и так знаем, что в текущий момент мы отправили запрос, если он успешен, то список избранных пополнился/уменьшился

2024-08-20 11:48 UTC, Lexeria requested changes

2024-08-20 11:48 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +function getActualized(allFilms: TFilm[], genre: string) {
А что именно получить актуализированное? Кажется, `FilmsList` (или просто `Films`, так как это и так список подразумевает) в конце стоило оставить

2024-08-20 11:48 UTC, Lexeria commented on project/src/components/genres-list.tsx
> +  setActualFilms: (films: TFilm[]) => void;
Понятно, почему этот тип подходит и какими рассуждениями и почему я до него дошел и предложил?

2024-08-20 12:01 UTC, GoveRaven commented on project/src/components/film-card-buttons.tsx
> +      dispatch(fetchFavoriteFilms());
Сейчас запрос с 42 строки перешёл в useEffect.
Я хотел переписать эту цифру, обозначающую количество фильмов в списке, так, чтобы оно просто увеличивалось и уменьшалось, не получая данных с сервера. 
Но во-первых, он должен изначально отображать число фильмов в списке, с этим всё просто. 
А во-вторых, он должен увеличивать или уменьшать число, а тут нужно задуматься. Тут уже появляются условия, 
ибо если фильм был уже в списке, то нужно уменьшать число, если не был - увеличивать. Был ли фильм изначально в списке можно узнать из пропса, а там сравнивать с нынешним значением, которое есть в стейте. Получается, если фильм был в списках и значение в стейте поменялось, то нужно уменьшать. Если фильма не было и поменялся стейт, то значение увеличивается. Если стейт не поменялся, то оставляем число, которое есть.
Вот я себе и расписал как это сделать. Звучит как описания на целую функцию

2024-08-20 12:02 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +function getActualized(allFilms: TFilm[], genre: string) {
я просто слово потерял при переименовании. Мой косяк

2024-08-20 12:03 UTC, GoveRaven commented on project/src/components/genres-list.tsx
> +  setActualFilms: (films: TFilm[]) => void;
Предложил потому что, во-первых, пишется лучше. А во-вторых, переписать его будет легче, чем предыдущий, если что-то поменяется.
Этот тип, потому что это сеттер, значит функция, которая ничего не получает. Но при этом сеттер что-то получает. Получает он тип `TFilm[]`

2024-08-25 18:52 UTC, Lexeria approved these changes

2024-08-25 18:52 UTC, merged