Прикрой меня тестом
GoveRaven/what-to-watch pull request #9
Opened 2024-08-31 14:55 UTC by GoveRaven

2024-09-20 14:21 UTC, Lexeria requested changes

2024-09-20 14:21 UTC, Lexeria commented on project/src/components/history-routes/browser-history.ts
> +export default browserHistory;
Лучше не использовать экспорт по умолчанию, давай вернем именованный экспорт? Это нужно, чтобы везде мы использовали именно то имя, которое указываем в этом файле. И в разных местах одна и та же сущность называлась одинаково. Если нужно переименовать в каком-то другом месте, то можно сделать так:
```js
import { browserHistory as otherName } from '../....';
```

2024-09-20 14:21 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  selectisSimilarFilmsLoading,
`is` должно начинать с большой буквы, чтобы соблюсти нейминг в стиле `camelCase`

2024-09-20 14:21 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  if (isFilmLoading && isSimilarFilmsLoading) {
А тут точно должно быть `&&`, а не `||`?

2024-09-20 14:21 UTC, Lexeria commented on project/src/components/history-routes/browser-history.ts
> +export default browserHistory;
Я увидел, что это сделано для создания мока в Jest, в котором указывается лишь путь до модуля. В таком случае могу попробовать посоветовать использовать одновременно именнованный и не именнованный экспорт:
```js
export const browserHistory = createBrowserHistory();
export default browserHistory;
```

Как минимум именованный экспорт еще удобен тем, что твой редактор кода или IDE автоматически будут предлагать и добавлять строчку с импортом выше, когда ты используешь указанное в модуле имя. Так что советую все же от него не отказываться и просто добавить экспорт по умолчанию для Jest

2024-09-20 14:21 UTC, Lexeria commented on project/src/services/middleware.test.ts
> +    expect(store.getActions()).toEqual([redirectToRoute(AppRoute.SignIn)]);
Не обязательно, но можно вытащить вызов `redirectToRoute(AppRoute.SignIn)` в переменную выше, чтобы не дублировать

2024-09-20 14:21 UTC, Lexeria commented on project/src/services/middleware.test.ts
> +  it('should not to be redirect "/login" because bad acction', () => {
Просто придирка, что после некоторых модальных глаголов не ставятся инфинитивы, а значит и частичка to. Плюс еще есть парочка ошибок других в формировании предложения, поэтому оставляю это замечание просто как напоминание и рекомендация писать описание на привычном русском и не париться. Тут никто не запрещает это делать, мы ж на русском проекте. Бывают исключения, но они обычно вызваны договоренностями в команде

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/data-slice/data-slice.test.ts
> +describe('data slice', () => {
Советую оставлять отступы между импортом и началом кода. Обычно есть хотя бы одна, иногда две строчки между ними

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/data-slice/selector.test.ts
> +import { datatype } from 'faker';
А понял, что за библиотека такая `faker` и как и зачем применяется `datatype`?

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/data-slice/selector.ts
> +  state: Pick<TState, SliceName.Data>
Это тип большой и везде дублируется, можно просто повыше вытащить его в `TDataState` или `TDataSliceState`

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/user-slice/selector.test.ts
> +  it('should return authorization status from store', () => {
Мелочь, но лучше отступ для читаемости добавить

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/user-slice/selector.ts
> +  state: Pick<TState, SliceName.User>
Тоже замечание про вынесение типа повыше, что везде `Pick` не дублировать

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/user-slice/user-slice.ts
> +        state.isAuthStatusChecked = true;
А мы точно должны везде это проставлять? У нас же `checkAuth` вызывается при старте приложения, а значит так или иначе мы поменяем статус после того, как действие выполнится

2024-09-20 14:21 UTC, Lexeria commented on project/src/types/store.ts
> +  isSimilarFilmsLoading: boolean;
Правильнее `are` в начале, так как множественное число

2024-09-20 14:21 UTC, Lexeria commented on project/src/utils/createMockComments.ts
> +export function createMockComments(): TReview {
Можно эту и другие функции для создания моков вытащить в отдельный файл один, чтобы по разным файлам не размазывать, так как у нас не так много моков создается, причем часть ты создаешь прямо в тестах без вынесения в утилзы

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/user-slice/selector.test.ts
> +      };
А у нас есть утилза для этого, или есть различия какие-то специфичные, чтобы ее тут не использовать?

2024-09-20 14:21 UTC, Lexeria commented on project/src/store/slices/user-slice/selector.test.ts
> +      const currentUser: TUser = {
Тот же вопрос про утилзу

2024-09-20 14:43 UTC, GoveRaven commented on project/src/components/history-routes/browser-history.ts
> +export default browserHistory;
изменил

2024-09-20 14:46 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  if (isFilmLoading && isSimilarFilmsLoading) {
Я думаю, что да. Если и фильм, и похожие фильмы не загрузились, то показывать лаудер. Зачем убирать лаудер, если один из двух элементов ещё не отображается на странице?

2024-09-20 14:56 UTC, GoveRaven commented on project/src/services/middleware.test.ts
> +    expect(store.getActions()).toEqual([redirectToRoute(AppRoute.SignIn)]);
сделал

2024-09-20 14:57 UTC, GoveRaven commented on project/src/store/slices/data-slice/data-slice.test.ts
> +describe('data slice', () => {
в VSCode визуально кажется, что отступ есть, поэтому я упустил его
![image](https://github.com/user-attachments/assets/0f30bfb9-6e15-4ffb-9143-03ee08e2db9c)

2024-09-20 15:00 UTC, GoveRaven commented on project/src/store/slices/data-slice/selector.test.ts
> +import { datatype } from 'faker';
`faker` применяется чтобы создавать фэйковые данные. 
`datatype `нужен, чтобы генерировать типы данных

2024-09-20 15:06 UTC, GoveRaven commented on project/src/store/slices/data-slice/selector.ts
> +  state: Pick<TState, SliceName.Data>
вынес в тип

2024-09-20 15:07 UTC, GoveRaven commented on project/src/store/slices/user-slice/selector.test.ts
> +  it('should return authorization status from store', () => {
добавил

2024-09-20 15:10 UTC, GoveRaven commented on project/src/store/slices/user-slice/selector.ts
> +  state: Pick<TState, SliceName.User>
добавил

2024-09-20 15:12 UTC, GoveRaven commented on project/src/store/slices/user-slice/user-slice.ts
> +        state.isAuthStatusChecked = true;
Я написал это из-за тестов. Так выходило, что после этих операций по тестам в стейте `isAuthStatusChecked  === UNKNOW`. И меня это напрягало. Хотел услышать твоё мнение

2024-09-20 15:17 UTC, GoveRaven commented on project/src/types/store.ts
> +  isSimilarFilmsLoading: boolean;
заменил

2024-09-20 15:21 UTC, GoveRaven commented on project/src/store/slices/user-slice/selector.test.ts
> +      };
идея с утилзами пришла мне не сразу, поэтому в какой-то момент я переписывал код. Этот остался тут из-за того, что я не доглядел
Добавил утилз

2024-09-20 15:22 UTC, GoveRaven commented on project/src/store/slices/user-slice/selector.test.ts
> +      const currentUser: TUser = {
тоже добавил

2024-09-20 15:24 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  if (isFilmLoading && isSimilarFilmsLoading) {
В том-то и дело, что один из двух, а не одновременно два. Тут нужно логическое ИЛИ, а не И

2024-09-20 15:26 UTC, Lexeria commented on project/src/store/slices/user-slice/user-slice.ts
> +        state.isAuthStatusChecked = true;
Менять рабочий код под тесты в таком ключе не очень хорошо, лучше менять тесты с учетом этого: например, не проверять `isAuthStatusChecked`, либо добавить в `beforeEach` или в тест-кейсы действие `checkAuth`, чтобы было по-честному, как происходит в приложении

2024-09-20 15:29 UTC, Lexeria requested changes

2024-09-20 15:29 UTC, Lexeria commented on project/src/pages/movie.tsx
> +  selectareSimilarFilmsLoading,
Переименовал на `are`, а замечание про `camelCase` пропустилось из-за этого, видимо

2024-09-20 15:29 UTC, Lexeria commented on project/src/store/slices/data-slice/selector.test.ts
> +      state[SliceName.Data];
Тут точно должен быть отступ? Как будто есть строчки подлиннее без него

2024-09-20 18:37 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  selectisSimilarFilmsLoading,
исправил

2024-09-20 18:40 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  if (isFilmLoading && isSimilarFilmsLoading) {
Да. До меня дошла моя ошибка. Я не так понял эти переменные. Исправил

2024-09-20 18:42 UTC, GoveRaven commented on project/src/pages/movie.tsx
> +  selectareSimilarFilmsLoading,
исправил

2024-09-20 18:44 UTC, GoveRaven commented on project/src/store/slices/data-slice/selector.test.ts
> +      state[SliceName.Data];
странно. В VSCode всё нормально. Может я залил изменения с прошедшемся преттиром, когда задивал какие-то изменения
![image](https://github.com/user-attachments/assets/187b9d58-7fb8-4f0b-97b9-860974ff9119)

2024-09-20 19:19 UTC, GoveRaven commented on project/src/store/slices/user-slice/user-slice.ts
> +        state.isAuthStatusChecked = true;
переписал тесты и слайс

2024-09-23 13:21 UTC, Lexeria requested changes

2024-09-23 13:21 UTC, Lexeria commented on project/src/pages/sign-in.test.tsx
> +    const expectedHeaderText = 'signInHeader';
Это не текст, а айдишник. Лучше дать другое название для переменной

А еще где-то айдишники в `camelCase`, а где-то в `snake-case`, советую выбрать единый стиль и его придерживаться

2024-09-23 13:21 UTC, Lexeria commented on project/src/pages/sign-in.test.tsx
> +describe('Компонент: sign-in', () => {
Это хоть и компонент, но все же речь про страницу. Названия компонентов, кст, обычно пишутся как-то так: `SignIn`

2024-09-23 13:21 UTC, Lexeria commented on project/src/pages/sign-in.test.tsx
> +describe('Компонент: sign-in', () => {
Можно еще добавить тест, где будет проверка на логин, что после нажатия на отправить с корректными логином и паролем все хорошо и происходит редирект. Аналогично вариант, что для невалидных данных ничего не работает

2024-09-23 13:21 UTC, Lexeria commented on project/src/pages/sign-in.tsx
> +                  data-testid="emailAddress"
Аналогичное замечание про единый стиль нейминга

2024-09-23 13:21 UTC, Lexeria commented on project/src/utils/mockcreaters.tsx
Забыл дефис в названии и мб очепятался в слове `creators`

2024-09-23 13:21 UTC, Lexeria commented on project/src/utils/mockcreaters.tsx
> +export function createMockComponentwithStore(
`With` с большой буквы, кажется

2024-09-23 13:21 UTC, Lexeria commented
Кажется, мы еще в процесс CI не вернули запуск тестов

2024-09-23 18:03 UTC, GoveRaven commented on project/src/utils/createMockComments.ts
> +export function createMockComments(): TReview {
вытащил в один файл

2024-09-23 18:04 UTC, GoveRaven commented on project/src/pages/sign-in.test.tsx
> +    const expectedHeaderText = 'signInHeader';
переписал

2024-09-23 18:05 UTC, GoveRaven commented on project/src/pages/sign-in.tsx
> +                  data-testid="emailAddress"
переименовал

2024-09-23 18:06 UTC, GoveRaven commented on project/src/utils/mockcreaters.tsx
исправил

2024-09-23 18:07 UTC, GoveRaven commented on project/src/utils/mockcreaters.tsx
> +export function createMockComponentwithStore(
переименовал

2024-09-23 20:12 UTC, Lexeria requested changes

2024-09-23 20:12 UTC, Lexeria commented on project/src/components/review-form.tsx
> +    <div className="add-review" >
А зачем здесь пробел?

2024-09-23 20:12 UTC, Lexeria commented on project/src/pages/add-review.test.tsx
> +describe('Компонент: add-review', () => {
Скорее страничка AddReview, но это мелочи

2024-09-23 20:12 UTC, Lexeria commented on project/src/pages/add-review.test.tsx
> +  beforeEach(() => {
Можно отступ добавить, но тож не критично

2024-09-23 20:12 UTC, Lexeria commented on project/src/pages/add-review.test.tsx
> +      'data/postComment/rejected',
Кажется, rejected на фоне того, что сетевые запросы в тестах не симулируются и завершаются не успешно. Чтобы все было хорошо, можно попробовать поработать с запросами:
```js
mockAxiosAdapter.onPost(APIRoute.PostComment).reply(200, fakeServerReplay);
// click
// Возможно, можно без диспатча и по-другому строчку ниже обыграть, просто если там серия диспатчей будет, то можно так
await Promise.all([
  mockStore.dispatch(postComment(reviewInfo)),
]);
const actions = store.getActions().map(({ type }) => type);
expect(actions.at(-1)).toEqual(postComment.fulfilled.type);
```

2024-09-23 20:12 UTC, Lexeria commented on project/src/utils/mock-creaters.tsx
> +  const mockStore: ReturnType<typeof mockStoreCreator> =
А точно нужно тип конкретизировать тут?

2024-09-23 20:12 UTC, Lexeria commented on project/src/utils/mock-store.ts
> +    DATA: mockDataSlice,
А у нас для названий слайсов не енамы используются?

2024-09-23 20:12 UTC, Lexeria commented on project/src/utils/mock-creaters.tsx
Кажется очепятка в названии осталась — `creatOrs`

2024-09-24 10:08 UTC, GoveRaven commented on project/src/components/review-form.tsx
> +    <div className="add-review" >
случайно поставил

2024-09-24 10:11 UTC, GoveRaven commented on project/src/utils/mock-creaters.tsx
> +  const mockStore: ReturnType<typeof mockStoreCreator> =
нет, не нужен

2024-09-24 10:12 UTC, GoveRaven commented on project/src/pages/add-review.test.tsx
> +  beforeEach(() => {
добавил

2024-09-24 10:12 UTC, GoveRaven commented on project/src/utils/mock-creaters.tsx
переименовал

2024-09-24 10:13 UTC, GoveRaven commented on project/src/utils/mock-store.ts
> +    DATA: mockDataSlice,
да, енам

2024-10-10 08:27 UTC, Lexeria approved these changes

2024-10-10 14:47 UTC, merged